//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#pragma mark Function Pointers and Blocks

typedef void (*CDUnknownFunctionPointerType)(void); // return type and parameters are unknown

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct CATransform3D {
    double m11;
    double m12;
    double m13;
    double m14;
    double m21;
    double m22;
    double m23;
    double m24;
    double m31;
    double m32;
    double m33;
    double m34;
    double m41;
    double m42;
    double m43;
    double m44;
};

struct CGAffineTransform {
    double a;
    double b;
    double c;
    double d;
    double tx;
    double ty;
};

struct CGPoint {
    double x;
    double y;
};

struct CGRect {
    struct CGPoint origin;
    struct CGSize size;
};

struct CGSize {
    double width;
    double height;
};

struct MMDB_description_s;

struct MMDB_entry_s {
    struct MMDB_s *_field1;
    unsigned int _field2;
};

struct MMDB_ipv4_start_node_s {
    unsigned short netmask;
    unsigned int node_value;
};

struct MMDB_lookup_result_s {
    _Bool _field1;
    struct MMDB_entry_s _field2;
    unsigned short _field3;
};

struct MMDB_metadata_s {
    unsigned int node_count;
    unsigned short record_size;
    unsigned short ip_version;
    char *database_type;
    struct {
        unsigned long long count;
        char **names;
    } languages;
    unsigned short binary_format_major_version;
    unsigned short binary_format_minor_version;
    unsigned long long build_epoch;
    struct {
        unsigned long long count;
        struct MMDB_description_s **descriptions;
    } description;
};

struct MMDB_s {
    unsigned int flags;
    char *filename;
    long long file_size;
    char *file_content;
    char *data_section;
    long long data_section_size;
    char *metadata_section;
    long long metadata_section_size;
    unsigned short full_record_byte_size;
    unsigned short depth;
    struct MMDB_ipv4_start_node_s ipv4_start_node;
    struct MMDB_metadata_s metadata;
};

struct UIEdgeInsets {
    double top;
    double left;
    double bottom;
    double right;
};

struct UIOffset {
    double horizontal;
    double vertical;
};

struct _NSRange {
    unsigned long long location;
    unsigned long long length;
};

struct _trie_memory_t;

struct _trie_t {
    struct _node_t *root;
    struct _trie_memory_t *first;
    struct _trie_memory_t *last;
};

struct ifaddrs {
    struct ifaddrs *_field1;
    char *_field2;
    unsigned int _field3;
    struct sockaddr *_field4;
    struct sockaddr *_field5;
    struct sockaddr *_field6;
    void *_field7;
};

struct in6_addr {
    union {
        unsigned char _field1[16];
        unsigned short _field2[8];
        unsigned int _field3[4];
    } _field1;
};

struct in_addr {
    unsigned int _field1;
};

struct internal_state;

struct sockaddr;

struct sockaddr_in {
    unsigned char _field1;
    unsigned char _field2;
    unsigned short _field3;
    struct in_addr _field4;
    char _field5[8];
};

struct sockaddr_in6 {
    unsigned char _field1;
    unsigned char _field2;
    unsigned short _field3;
    unsigned int _field4;
    struct in6_addr _field5;
    unsigned int _field6;
};

struct sockaddr_un {
    unsigned char _field1;
    unsigned char _field2;
    char _field3[104];
};

struct trie_ctx_s {
    int _field1;
    int _field2;
    int _field3;
    int _field4;
    int _field5;
    void *_field6;
};

struct z_stream_s {
    char *next_in;
    unsigned int avail_in;
    unsigned long long total_in;
    char *next_out;
    unsigned int avail_out;
    unsigned long long total_out;
    char *msg;
    struct internal_state *state;
    CDUnknownFunctionPointerType zalloc;
    CDUnknownFunctionPointerType zfree;
    void *opaque;
    int data_type;
    unsigned long long adler;
    unsigned long long reserved;
};

#pragma mark Typedef'd Structures

typedef struct {
    unsigned long long _field1;
    id *_field2;
    unsigned long long *_field3;
    unsigned long long _field4[5];
} CDStruct_70511ce9;

typedef struct {
    long long version;
    void *info;
    CDUnknownFunctionPointerType retain;
    CDUnknownFunctionPointerType release;
    CDUnknownFunctionPointerType copyDescription;
} CDStruct_4210025a;

