//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSManagedObjectContext, NSManagedObjectModel, NSPersistentStoreCoordinator, NSString;

@interface CoreDataManager : NSObject
{
    NSManagedObjectContext *_managedObjectContext;
    NSManagedObjectModel *_managedObjectModel;
    NSPersistentStoreCoordinator *_persistentStoreCoordinator;
    NSString *_databaseName;
    NSString *_modelName;
}

+ (id)sharedManager;
+ (id)instance;
@property(copy, nonatomic) NSString *modelName; // @synthesize modelName=_modelName;
@property(copy, nonatomic) NSString *databaseName; // @synthesize databaseName=_databaseName;
- (void).cxx_destruct;
- (void)createApplicationSupportDirIfNeeded:(id)arg1;
- (_Bool)isOSX;
- (id)sqliteStoreURL;
- (id)persistentStoreCoordinatorWithStoreType:(id)arg1 storeURL:(id)arg2;
- (id)applicationSupportDirectory;
- (id)applicationDocumentsDirectory;
- (_Bool)saveContext;
- (void)useInMemoryStore;
@property(readonly, nonatomic) NSPersistentStoreCoordinator *persistentStoreCoordinator; // @synthesize persistentStoreCoordinator=_persistentStoreCoordinator;
@property(readonly, nonatomic) NSManagedObjectModel *managedObjectModel; // @synthesize managedObjectModel=_managedObjectModel;
@property(readonly, nonatomic) NSManagedObjectContext *managedObjectContext; // @synthesize managedObjectContext=_managedObjectContext;
- (id)appName;

@end

