//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/NSTextStorage.h>

@class NSArray, NSMutableAttributedString, NSMutableDictionary, UIColor, UIFont;

@interface CYRTextStorage : NSTextStorage
{
    NSArray *_tokens;
    UIFont *_defaultFont;
    UIColor *_defaultTextColor;
    NSMutableAttributedString *_attributedString;
    NSMutableDictionary *_regularExpressionCache;
}

@property(retain, nonatomic) NSMutableDictionary *regularExpressionCache; // @synthesize regularExpressionCache=_regularExpressionCache;
@property(retain, nonatomic) NSMutableAttributedString *attributedString; // @synthesize attributedString=_attributedString;
@property(retain, nonatomic) UIColor *defaultTextColor; // @synthesize defaultTextColor=_defaultTextColor;
@property(retain, nonatomic) UIFont *defaultFont; // @synthesize defaultFont=_defaultFont;
@property(retain, nonatomic) NSArray *tokens; // @synthesize tokens=_tokens;
- (void).cxx_destruct;
- (id)expressionForDefinition:(id)arg1;
- (void)applyStylesToRange:(struct _NSRange)arg1;
- (void)update;
- (void)performReplacementsForRange:(struct _NSRange)arg1;
- (void)processEditing;
- (void)setAttributes:(id)arg1 range:(struct _NSRange)arg2;
- (void)replaceCharactersInRange:(struct _NSRange)arg1 withString:(id)arg2;
- (id)attributesAtIndex:(unsigned long long)arg1 effectiveRange:(struct _NSRange *)arg2;
- (id)string;
- (id)init;

@end

