//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "GCDAsyncUdpSocketDelegate-Protocol.h"

@class GCDAsyncUdpSocket, NSString;
@protocol DLWAsyncDnsDelegate, OS_dispatch_queue;

@interface DLWAsyncDns : NSObject <GCDAsyncUdpSocketDelegate>
{
    NSString *_queryHost;
    id _userData;
    id <DLWAsyncDnsDelegate> _delegate;
    NSObject<OS_dispatch_queue> *_queue;
    GCDAsyncUdpSocket *_udpSocket;
    NSObject<OS_dispatch_queue> *_completionQueue;
}

+ (id)getDNSServers;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *completionQueue; // @synthesize completionQueue=_completionQueue;
@property(retain, nonatomic) GCDAsyncUdpSocket *udpSocket; // @synthesize udpSocket=_udpSocket;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(nonatomic) __weak id <DLWAsyncDnsDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) id userData; // @synthesize userData=_userData;
@property(copy, nonatomic) NSString *queryHost; // @synthesize queryHost=_queryHost;
- (void).cxx_destruct;
- (void)udpSocketDidClose:(id)arg1 withError:(id)arg2;
- (void)udpSocket:(id)arg1 didReceiveData:(id)arg2 fromAddress:(id)arg3 withFilterContext:(id)arg4;
- (void)udpSocket:(id)arg1 didNotSendDataWithTag:(long long)arg2 dueToError:(id)arg3;
- (void)lookup:(id)arg1 server:(id)arg2 port:(unsigned short)arg3;
- (id)constructDnsRequest:(id)arg1;
- (id)parseDnsResponse:(id)arg1;
- (id)gaiError:(int)arg1;
- (id)badParamError:(id)arg1;
- (_Bool)isValidatIP:(id)arg1;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1 completionQueue:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

