//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DLWViewController.h"

#import "DLWWebUploaderDelegate-Protocol.h"

@class DLWWebUploader, NSString;

@interface DLWConfigUploadViewController : DLWViewController <DLWWebUploaderDelegate>
{
    DLWWebUploader *_webUploader;
}

@property(retain, nonatomic) DLWWebUploader *webUploader; // @synthesize webUploader=_webUploader;
- (void).cxx_destruct;
- (void)webUploader:(id)arg1 didDeleteItemAtPath:(id)arg2;
- (void)webUploader:(id)arg1 didUploadFileAtPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 willLoadCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)dealloc;
- (void)setupTableViewManager;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

