//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UISearchResultsUpdating-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class DLWConfigReader, NSMutableArray, NSString, UITableView;

@interface DLWConfigKeyValuesSearchController : UIViewController <UITableViewDelegate, UITableViewDataSource, UISearchResultsUpdating>
{
    _Bool _loadMoreAvailable;
    UITableView *_tableView;
    DLWConfigReader *_configReader;
    NSMutableArray *_searchData;
    NSString *_searchString;
    NSString *_section;
}

@property(copy, nonatomic) NSString *section; // @synthesize section=_section;
@property(copy, nonatomic) NSString *searchString; // @synthesize searchString=_searchString;
@property(nonatomic) _Bool loadMoreAvailable; // @synthesize loadMoreAvailable=_loadMoreAvailable;
@property(retain, nonatomic) NSMutableArray *searchData; // @synthesize searchData=_searchData;
@property(retain, nonatomic) DLWConfigReader *configReader; // @synthesize configReader=_configReader;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)configItemWillChangeNotification:(id)arg1;
- (void)updateSearchResultsForSearchController:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithConfigReader:(id)arg1 section:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

