//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CYRTextView.h"

@class UIFont;

@interface DLWConfigTextView : CYRTextView
{
    UIFont *_defaultFont;
}

@property(retain, nonatomic) UIFont *defaultFont; // @synthesize defaultFont=_defaultFont;
- (void).cxx_destruct;
- (void)setSyntaxText:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;
- (id)solverTokens;
- (void)commonSetup;
- (id)initWithFrame:(struct CGRect)arg1;

@end

