//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DLWViewController.h"

@interface DLWDebugLogsViewController : DLWViewController
{
}

- (void)reloadLoggingFiles;
- (void)moreButtonTouched:(id)arg1;
- (void)setupMoreButton;
- (void)setupTableViewManager;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)init;

@end

