//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DLWViewController.h"

@class DLWConfigTextView, NSURL, UIButton;

@interface DLWEditorViewController : DLWViewController
{
    _Bool _textViewLoaded;
    _Bool _editingMode;
    NSURL *_URL;
    UIButton *_saveButton;
    DLWConfigTextView *_textView;
}

@property(nonatomic) _Bool editingMode; // @synthesize editingMode=_editingMode;
@property(nonatomic) _Bool textViewLoaded; // @synthesize textViewLoaded=_textViewLoaded;
@property(retain, nonatomic) DLWConfigTextView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) UIButton *saveButton; // @synthesize saveButton=_saveButton;
@property(retain, nonatomic) NSURL *URL; // @synthesize URL=_URL;
- (void).cxx_destruct;
- (void)UIKeyboardWillHideNotification:(id)arg1;
- (void)UIKeyboardDidShowNotification:(id)arg1;
- (_Bool)shouldAutorotate;
- (void)viewWillLayoutSubviews;
- (_Bool)prefersStatusBarHidden;
- (void)saveButtonTouched;
- (void)setupSaveButton;
- (void)readRemoteConfigTask;
- (void)readLocalConfigTask;
- (void)readConfigDatabaseTask;
- (void)readConfigTask;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithURL:(id)arg1;

@end

