//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface DLWEmojiFlag : NSObject
{
    NSDictionary *_emojiFlags;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSDictionary *emojiFlags; // @synthesize emojiFlags=_emojiFlags;
- (void).cxx_destruct;
- (id)detectPrefixFlag:(id)arg1;
- (id)init;

@end

