//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface DLWFontIcon : NSObject
{
}

+ (id)defaultColor;
+ (id)renderImageWithCoreGraphicsWithIconName:(id)arg1 iconColor:(id)arg2 iconSize:(double)arg3 imageSize:(struct CGSize)arg4;
+ (id)renderImageWithNSStringDrawingWithIconName:(id)arg1 iconColor:(id)arg2 iconSize:(double)arg3 imageSize:(struct CGSize)arg4;
+ (id)imageWithIcon:(id)arg1 iconColor:(id)arg2 iconSize:(double)arg3 imageSize:(struct CGSize)arg4;
+ (id)imageWithIcon:(id)arg1 size:(double)arg2 color:(id)arg3;
+ (void)label:(id)arg1 setIcon:(id)arg2 size:(double)arg3 color:(id)arg4 sizeToFit:(_Bool)arg5;
+ (id)labelWithIcon:(id)arg1 size:(double)arg2 color:(id)arg3;
+ (void)registerDLWFontIconFont;
+ (id)fontWithSize:(double)arg1;

@end

