//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DLWViewController.h"

#import "RETableViewCellDelegate-Protocol.h"
#import "RETableViewManagerDelegate-Protocol.h"
#import "UIViewControllerPreviewingDelegate-Protocol.h"

@class DLWMessageChannel, DLWRadioItem, NETunnelProviderManager, NSMutableArray, NSMutableSet, NSObject, NSString, REBoolItem, RETableViewSection, UIActivityIndicatorView, UIBarButtonItem;
@protocol OS_dispatch_source;

@interface DLWHomeViewController : DLWViewController <RETableViewCellDelegate, RETableViewManagerDelegate, UIViewControllerPreviewingDelegate>
{
    long long _activedCount;
    NSObject<OS_dispatch_source> *_vpnStatusTimer;
    DLWMessageChannel *_messageChannel;
    DLWRadioItem *_routingRadioItem;
    NETunnelProviderManager *_tunnelProviderManager;
    NSMutableArray *_waitingDeletes;
    NSMutableSet *_pasteboardSet;
    REBoolItem *_vpnStatusItem;
    RETableViewSection *_hostSection;
    UIActivityIndicatorView *_pingIndicatorView;
    UIBarButtonItem *_deleteButtonItem;
    UIBarButtonItem *_doneButtonItem;
    UIBarButtonItem *_leftBarButtonItem;
    UIBarButtonItem *_rightBarButtonItem;
}

+ (void)initialize;
@property(retain, nonatomic) UIBarButtonItem *rightBarButtonItem; // @synthesize rightBarButtonItem=_rightBarButtonItem;
@property(retain, nonatomic) UIBarButtonItem *leftBarButtonItem; // @synthesize leftBarButtonItem=_leftBarButtonItem;
@property(retain, nonatomic) UIBarButtonItem *doneButtonItem; // @synthesize doneButtonItem=_doneButtonItem;
@property(retain, nonatomic) UIBarButtonItem *deleteButtonItem; // @synthesize deleteButtonItem=_deleteButtonItem;
@property(retain, nonatomic) UIActivityIndicatorView *pingIndicatorView; // @synthesize pingIndicatorView=_pingIndicatorView;
@property(retain, nonatomic) RETableViewSection *hostSection; // @synthesize hostSection=_hostSection;
@property(retain, nonatomic) REBoolItem *vpnStatusItem; // @synthesize vpnStatusItem=_vpnStatusItem;
@property(retain, nonatomic) NSMutableSet *pasteboardSet; // @synthesize pasteboardSet=_pasteboardSet;
@property(retain, nonatomic) NSMutableArray *waitingDeletes; // @synthesize waitingDeletes=_waitingDeletes;
@property(retain, nonatomic) NETunnelProviderManager *tunnelProviderManager; // @synthesize tunnelProviderManager=_tunnelProviderManager;
@property(retain, nonatomic) DLWRadioItem *routingRadioItem; // @synthesize routingRadioItem=_routingRadioItem;
@property(retain, nonatomic) DLWMessageChannel *messageChannel; // @synthesize messageChannel=_messageChannel;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *vpnStatusTimer; // @synthesize vpnStatusTimer=_vpnStatusTimer;
@property(nonatomic) long long activedCount; // @synthesize activedCount=_activedCount;
- (void).cxx_destruct;
- (_Bool)accessibilityPerformMagicTap;
- (id)tabImageName;
- (id)tabTitle;
- (void)UIApplicationDidBecomeActiveNotification;
- (void)NEVPNStatusDidChangeNotification:(id)arg1;
- (void)extensionMessageWillSendNotification:(id)arg1;
- (void)configDidChangeNotification:(id)arg1;
- (void)previewingContext:(id)arg1 commitViewController:(id)arg2;
- (id)previewingContext:(id)arg1 viewControllerForLocation:(struct CGPoint)arg2;
- (void)tableView:(id)arg1 didLoadCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 editActionsForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)stopTunnelProviderManager;
- (void)startTunnelProviderManager;
- (void)handleLongPressGestureRecognizer:(id)arg1;
- (void)handleDebugGestureRecognizer:(id)arg1;
- (void)pinchGestureRecognizer:(id)arg1;
- (_Bool)updateVPNStatusItemIfNeeded;
- (void)pingButtonTouched;
- (void)reassertTunnelProvider;
- (void)sortButtonTouched;
- (void)deleteButtonTouchAtIndexPath:(id)arg1;
- (void)qrCodeButtonTouched:(id)arg1;
- (void)updateButtonTouched:(id)arg1;
- (void)duplicateButtonTouched:(id)arg1;
- (void)deleteButtonTouched;
- (void)doneButtonTouched;
- (void)resetBarButtonItem;
- (void)updateAllHostsOrder;
- (void)addCopiedHostsTask:(id)arg1;
- (void)dlw_addButtonTouched;
- (void)dlw_qrCodeScaned:(id)arg1;
- (void)lookupHostsFlag;
- (void)loadHostsSection;
- (void)reloadHostsSection;
- (void)setupTunnelProviderManager;
- (void)setupTableViewManager;
- (void)setupGestureRecognizer;
- (void)reloadVpnStatusWithTitle:(id)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

