//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class UIButton, UITextView;

@interface DLWHostsViewController : UIViewController
{
    UIButton *_saveButton;
    UITextView *_textView;
}

@property(retain, nonatomic) UITextView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) UIButton *saveButton; // @synthesize saveButton=_saveButton;
- (void).cxx_destruct;
- (void)UIKeyboardWillHideNotification:(id)arg1;
- (void)UIKeyboardDidShowNotification:(id)arg1;
- (_Bool)accessibilityPerformEscape;
- (_Bool)shouldAutorotate;
- (void)viewWillLayoutSubviews;
- (void)saveButtonTouched;
- (void)setupSaveButton;
- (void)setupTextView;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

@end

