//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface DLWHostsManager : NSObject
{
    struct __CFDictionary *_records;
    long long _wildcards;
}

+ (id)sharedInstance;
@property(nonatomic) long long wildcards; // @synthesize wildcards=_wildcards;
- (id)lookupIpWithDomain:(id)arg1 isPtr:(_Bool *)arg2;
- (id)lookupAddrressWithDomain:(id)arg1;
- (void)parseWithFile:(id)arg1 supportsPtr:(_Bool)arg2;
- (void)reload;
- (void)dealloc;
- (id)init;

@end

