//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DLWViewController.h"

@class NSDateFormatter;

@interface DLWiCloudViewController : DLWViewController
{
    NSDateFormatter *_dateFormatter;
}

@property(retain, nonatomic) NSDateFormatter *dateFormatter; // @synthesize dateFormatter=_dateFormatter;
- (void).cxx_destruct;
- (void)confirmDeleteWithBlock:(CDUnknownBlockType)arg1;
- (void)syncAllFiles;
- (void)backupAllFiles;
- (void)deleteAllBackups;
- (void)confirmOverwriteWithBlock:(CDUnknownBlockType)arg1;
- (void)downloadGroups;
- (void)backupGroups;
- (void)downloadScenes;
- (void)backupScenes;
- (void)deleteLocalServers;
- (void)deleteBackupServers;
- (void)setupTableViewManager;
- (void)viewDidLoad;
- (id)init;

@end

