//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData;
@protocol DLWIcmpSocketDelegate, OS_dispatch_queue;

@interface DLWIcmpSocket : NSObject
{
    _Bool _success;
    unsigned short _identifier;
    int _socket;
    id <DLWIcmpSocketDelegate> _delegate;
    double _startedTime;
    double _finishedTime;
    long long _sequenceNumber;
    id _userData;
    NSData *_address;
    NSObject<OS_dispatch_queue> *_queue;
}

@property(nonatomic) int socket; // @synthesize socket=_socket;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(nonatomic) _Bool success; // @synthesize success=_success;
@property(retain, nonatomic) NSData *address; // @synthesize address=_address;
@property(retain, nonatomic) id userData; // @synthesize userData=_userData;
@property(nonatomic) unsigned short identifier; // @synthesize identifier=_identifier;
@property(nonatomic) long long sequenceNumber; // @synthesize sequenceNumber=_sequenceNumber;
@property(nonatomic) double finishedTime; // @synthesize finishedTime=_finishedTime;
@property(nonatomic) double startedTime; // @synthesize startedTime=_startedTime;
@property(nonatomic) __weak id <DLWIcmpSocketDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (double)seconds;
- (void)disconnect;
- (void)sendIcmpPacket;
- (void)connectToHost:(id)arg1;
- (void)notifyWithSuccess:(_Bool)arg1;
- (id)initWithDelegate:(id)arg1 dispatchQueue:(id)arg2;

@end

