//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FMDatabaseQueue, NSString;

@interface DLWLoggingManager : NSObject
{
    FMDatabaseQueue *_queue;
    NSString *_type;
}

+ (id)proxyManager;
+ (id)dnsManager;
+ (void)initialize;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) FMDatabaseQueue *queue; // @synthesize queue=_queue;
- (void).cxx_destruct;
- (void)truncate;
- (void)saveDnsRecord:(id)arg1;
- (void)saveProxyRecord:(id)arg1;
- (void)close;
- (void)open;
- (void)autoDeleteLog;
- (id)initWithType:(id)arg1;

@end

