//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface DLWLoggingReader : NSObject
{
    NSString *_path;
}

@property(copy, nonatomic) NSString *path; // @synthesize path=_path;
- (void).cxx_destruct;
- (void)truncate;
- (id)queryWithKeyword:(id)arg1;
- (id)queryWithKeyword:(id)arg1 lessThan:(long long)arg2;
- (id)queryWithKeyword:(id)arg1 greaterThan:(long long)arg2;
- (id)queryWithType:(id)arg1 lessThan:(long long)arg2;
- (id)queryWithType:(id)arg1 greaterThan:(long long)arg2;
- (id)queryWithLessThan:(long long)arg1;
- (id)queryWithGreaterThan:(long long)arg1;
- (id)executeQuery:(id)arg1;
- (id)initWithPath:(id)arg1;

@end

