//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UISearchControllerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "UIViewControllerPreviewingDelegate-Protocol.h"

@class DLWLoggingReader, DLWLoggingSearchController, NSMutableArray, NSString, UISearchController, UISegmentedControl, UITableView;

@interface DLWLoggingViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, UISearchControllerDelegate, UIViewControllerPreviewingDelegate>
{
    _Bool _loadMoreAvailable;
    _Bool _proxyLogging;
    NSString *_file;
    UITableView *_tableView;
    UISegmentedControl *_segmentedControl;
    DLWLoggingReader *_loggingReader;
    NSMutableArray *_data;
    UISearchController *_searchController;
    DLWLoggingSearchController *_searchResultsController;
}

@property(nonatomic) _Bool proxyLogging; // @synthesize proxyLogging=_proxyLogging;
@property(retain, nonatomic) DLWLoggingSearchController *searchResultsController; // @synthesize searchResultsController=_searchResultsController;
@property(retain, nonatomic) UISearchController *searchController; // @synthesize searchController=_searchController;
@property(nonatomic) _Bool loadMoreAvailable; // @synthesize loadMoreAvailable=_loadMoreAvailable;
@property(retain, nonatomic) NSMutableArray *data; // @synthesize data=_data;
@property(retain, nonatomic) DLWLoggingReader *loggingReader; // @synthesize loggingReader=_loggingReader;
@property(retain, nonatomic) UISegmentedControl *segmentedControl; // @synthesize segmentedControl=_segmentedControl;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(copy, nonatomic) NSString *file; // @synthesize file=_file;
- (void).cxx_destruct;
- (void)previewingContext:(id)arg1 commitViewController:(id)arg2;
- (id)previewingContext:(id)arg1 viewControllerForLocation:(struct CGPoint)arg2;
- (void)willDismissSearchController:(id)arg1;
- (void)willPresentSearchController:(id)arg1;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 performAction:(SEL)arg2 forRowAtIndexPath:(id)arg3 withSender:(id)arg4;
- (_Bool)tableView:(id)arg1 canPerformAction:(SEL)arg2 forRowAtIndexPath:(id)arg3 withSender:(id)arg4;
- (_Bool)tableView:(id)arg1 shouldShowMenuForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)sendTruncateTask;
- (void)loadMoreData;
- (void)reloadData;
- (id)currentRuleType;
- (void)UIControlEventValueChanged:(id)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewDidLayoutSubviews;
- (void)setupRefreshButton;
- (void)setupTableView;
- (void)setupSegmentedControl;
- (void)viewDidLoad;
- (id)initWithFile:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

