//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSFileHandle, NSFileManager, NSString;
@protocol OS_dispatch_source;

@interface DLWMessageChannel : NSObject
{
    NSObject<OS_dispatch_source> *_source;
    NSString *_filePath;
    CDUnknownBlockType _listenerBlock;
    NSFileHandle *_writeFileHandle;
    NSFileHandle *_readFileHandle;
    NSFileManager *_fileManager;
    NSString *_listenerIdentifier;
}

+ (id)ping;
+ (id)tunnel;
@property(copy, nonatomic) NSString *listenerIdentifier; // @synthesize listenerIdentifier=_listenerIdentifier;
@property(retain, nonatomic) NSFileManager *fileManager; // @synthesize fileManager=_fileManager;
@property(retain, nonatomic) NSFileHandle *readFileHandle; // @synthesize readFileHandle=_readFileHandle;
@property(retain, nonatomic) NSFileHandle *writeFileHandle; // @synthesize writeFileHandle=_writeFileHandle;
@property(copy, nonatomic) CDUnknownBlockType listenerBlock; // @synthesize listenerBlock=_listenerBlock;
@property(copy, nonatomic) NSString *filePath; // @synthesize filePath=_filePath;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *source; // @synthesize source=_source;
- (void).cxx_destruct;
- (void)dealloc;
- (void)parseMessage;
- (id)filePathForListener;
- (void)postMessage:(id)arg1;
- (void)stopListening;
- (void)listenWithBlock:(CDUnknownBlockType)arg1;
- (id)initWithIdentifier:(id)arg1;

@end

