//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UINavigationController.h>

#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"

@class NSString, ZFModalTransitionAnimator;
@protocol UINavigationControllerDelegate;

@interface DLWNavigationController : UINavigationController <UINavigationControllerDelegate, UIGestureRecognizerDelegate>
{
    _Bool _duringPushAnimation;
    id <UINavigationControllerDelegate> _realDelegate;
    ZFModalTransitionAnimator *_animator;
}

@property(retain, nonatomic) ZFModalTransitionAnimator *animator; // @synthesize animator=_animator;
@property(nonatomic) __weak id <UINavigationControllerDelegate> realDelegate; // @synthesize realDelegate=_realDelegate;
@property(nonatomic, getter=isDuringPushAnimation) _Bool duringPushAnimation; // @synthesize duringPushAnimation=_duringPushAnimation;
- (void).cxx_destruct;
- (long long)preferredStatusBarStyle;
- (void)forwardInvocation:(id)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (_Bool)respondsToSelector:(SEL)arg1;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (id)navigationController:(id)arg1 interactionControllerForAnimationController:(id)arg2;
- (id)navigationController:(id)arg1 animationControllerForOperation:(long long)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;
- (void)navigationController:(id)arg1 didShowViewController:(id)arg2 animated:(_Bool)arg3;
- (void)setDelegate:(id)arg1;
- (void)viewDidLoad;
- (void)setupTransitionAnimator;
- (id)initWithRootViewController:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

