//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DLWViewController.h"

@class NSArray, NSMutableDictionary, NSString, RERadioItem, RETextItem;
@protocol DLWObfuscationViewControllerDelegate;

@interface DLWObfuscationViewController : DLWViewController
{
    id <DLWObfuscationViewControllerDelegate> _delegate;
    NSMutableDictionary *_attributes;
    RERadioItem *_protoRadioItem;
    RETextItem *_protoParamTextItem;
    RERadioItem *_obfsRadioItem;
    RETextItem *_obfsParamTextItem;
    RETextItem *_pathTextItem;
    NSString *_obfs;
    NSArray *_obfuscations;
}

@property(retain, nonatomic) NSArray *obfuscations; // @synthesize obfuscations=_obfuscations;
@property(retain, nonatomic) NSString *obfs; // @synthesize obfs=_obfs;
@property(retain, nonatomic) RETextItem *pathTextItem; // @synthesize pathTextItem=_pathTextItem;
@property(retain, nonatomic) RETextItem *obfsParamTextItem; // @synthesize obfsParamTextItem=_obfsParamTextItem;
@property(retain, nonatomic) RERadioItem *obfsRadioItem; // @synthesize obfsRadioItem=_obfsRadioItem;
@property(retain, nonatomic) RETextItem *protoParamTextItem; // @synthesize protoParamTextItem=_protoParamTextItem;
@property(retain, nonatomic) RERadioItem *protoRadioItem; // @synthesize protoRadioItem=_protoRadioItem;
@property(retain, nonatomic) NSMutableDictionary *attributes; // @synthesize attributes=_attributes;
@property(nonatomic) __weak id <DLWObfuscationViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)updateAttributes;
- (void)updateRadioAttributes;
- (void)setupTableViewManager;
- (void)setupAttributes;
- (void)viewDidLoad;
- (id)init;
- (id)initWithAttributes:(id)arg1;

@end

