//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "DLWIcmpSocketDelegate-Protocol.h"
#import "DLWTcpSocketDelegate-Protocol.h"

@class DLWMessageChannel, NSArray, NSMutableArray, NSMutableDictionary, NSString;
@protocol OS_dispatch_queue, OS_dispatch_source;

@interface DLWPingManager : NSObject <DLWTcpSocketDelegate, DLWIcmpSocketDelegate>
{
    void *IsOnSocketQueueOrTargetQueueKey;
    _Bool _busying;
    CDUnknownBlockType _progressBlock;
    NSArray *_addresses;
    long long _taskNumber;
    NSMutableArray *_tasks;
    NSMutableDictionary *_result;
    DLWMessageChannel *_messageChannel;
    NSObject<OS_dispatch_queue> *_queue;
    NSObject<OS_dispatch_source> *_timer;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) DLWMessageChannel *messageChannel; // @synthesize messageChannel=_messageChannel;
@property(retain, nonatomic) NSMutableDictionary *result; // @synthesize result=_result;
@property(retain, nonatomic) NSMutableArray *tasks; // @synthesize tasks=_tasks;
@property(nonatomic) long long taskNumber; // @synthesize taskNumber=_taskNumber;
@property(retain, nonatomic) NSArray *addresses; // @synthesize addresses=_addresses;
@property(nonatomic) _Bool busying; // @synthesize busying=_busying;
@property(copy, nonatomic) CDUnknownBlockType progressBlock; // @synthesize progressBlock=_progressBlock;
- (void).cxx_destruct;
- (void)icmpSocket:(id)arg1 didFinishWithSuccess:(_Bool)arg2;
- (void)tcpSocket:(id)arg1 didFinishWithSuccess:(_Bool)arg2;
- (void)pingUsingMessageChannel;
- (void)pingUsingIcmp;
- (void)pingUsingTcp;
- (void)cancel;
- (_Bool)isBusying;
- (void)localPing;
- (void)startTimeoutTimer;
- (void)pingAddresses:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (_Bool)isAppExtension;
- (void)performBlock:(CDUnknownBlockType)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

