//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface DLWPingSummary : NSObject
{
    double _seconds;
    long long _count;
    long long _failed;
    long long _success;
}

@property(nonatomic) long long success; // @synthesize success=_success;
@property(nonatomic) long long failed; // @synthesize failed=_failed;
@property(nonatomic) long long count; // @synthesize count=_count;
@property(nonatomic) double seconds; // @synthesize seconds=_seconds;
- (id)description;

@end

