//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSDictionary, UIImage;

@interface DLWQRCodeViewController : UIViewController
{
    NSDictionary *_config;
    UIImage *_qrImage;
}

@property(retain, nonatomic) UIImage *qrImage; // @synthesize qrImage=_qrImage;
@property(retain, nonatomic) NSDictionary *config; // @synthesize config=_config;
- (void).cxx_destruct;
- (id)resizeImage:(id)arg1 withQuality:(int)arg2 rate:(double)arg3;
- (id)createQRForString:(id)arg1;
- (void)shareButtonTouched;
- (void)viewDidLoad;
- (id)initWithConfig:(id)arg1;

@end

