//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DLWSceneItem, DLWSceneManager, DLWServer, NSString;
@protocol OS_dispatch_queue;

@interface DLWRoutingManager : NSObject
{
    void *IsOnSocketQueueOrTargetQueueKey;
    DLWServer *currentServer;
    id _group;
    NSString *_routing;
    DLWSceneItem *_scene;
    DLWSceneManager *_sceneManager;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (id)sharedInstance;
@property(retain) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain) DLWSceneManager *sceneManager; // @synthesize sceneManager=_sceneManager;
@property(retain) DLWSceneItem *scene; // @synthesize scene=_scene;
@property(copy) NSString *routing; // @synthesize routing=_routing;
@property(retain) id group; // @synthesize group=_group;
- (void).cxx_destruct;
- (_Bool)isServerUnseted;
- (void)clear;
- (_Bool)isGroupNeeded;
- (_Bool)isConfigRouting;
- (_Bool)isDirectRouting;
- (_Bool)isProxyRouting;
- (void)updateGroupServerAtIndex:(long long)arg1;
- (id)groupServerAtIndex:(long long)arg1;
- (id)groupName;
- (id)groupServers;
- (id)ruleServers;
- (id)ruleFilePath;
- (void)reloadSettings;
- (void)asyncReload;
- (void)loadTunnelSettings;
- (void)checkRuleFile:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)reload;
- (void)setServer:(id)arg1;
- (id)currentServer;
- (void)performBlock:(CDUnknownBlockType)arg1;
- (id)init;

@end

