//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RERadioItem.h"

@class NSString;

@interface DLWRadioItem : RERadioItem
{
    NSString *_originalValue;
}

@property(copy, nonatomic) NSString *originalValue; // @synthesize originalValue=_originalValue;
- (void).cxx_destruct;
- (void)setValue:(id)arg1;

@end

