//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DLWRuleMatcherResult, DLWTrieRule, NSArray, NSString;

@interface DLWRuleMatcher : NSObject
{
    struct _trie_t ipv4set;
    struct _trie_t ipv6set;
    _Bool _serverUnseted;
    double _ruleModified;
    unsigned long long _ruleSize;
    NSArray *_userAgents;
    NSArray *_hostnames;
    DLWTrieRule *_trieRule;
    NSString *_ruleFilePath;
    DLWRuleMatcherResult *_defaultResult;
}

+ (id)sharedInstance;
@property(retain, nonatomic) DLWRuleMatcherResult *defaultResult; // @synthesize defaultResult=_defaultResult;
@property(copy, nonatomic) NSString *ruleFilePath; // @synthesize ruleFilePath=_ruleFilePath;
@property(retain, nonatomic) DLWTrieRule *trieRule; // @synthesize trieRule=_trieRule;
@property(retain, nonatomic) NSArray *hostnames; // @synthesize hostnames=_hostnames;
@property(retain, nonatomic) NSArray *userAgents; // @synthesize userAgents=_userAgents;
@property(nonatomic) _Bool serverUnseted; // @synthesize serverUnseted=_serverUnseted;
@property(nonatomic) unsigned long long ruleSize; // @synthesize ruleSize=_ruleSize;
@property(nonatomic) double ruleModified; // @synthesize ruleModified=_ruleModified;
- (void).cxx_destruct;
- (id)ruleForDomain:(id)arg1 userAgent:(id)arg2 resolve:(_Bool)arg3;
- (id)ruleForIp:(id)arg1 userAgent:(id)arg2 resolve:(_Bool)arg3;
- (id)matcherResultForDomain:(id)arg1 resolve:(_Bool)arg2;
- (id)matcherResultForIp:(id)arg1 resolve:(_Bool)arg2;
- (id)matcherResultForHost:(id)arg1 resolve:(_Bool)arg2;
- (id)ruleOfUserAgent:(id)arg1;
- (_Bool)containsMitmHostname:(const char *)arg1;
- (id)ruleOfIp:(id)arg1;
- (id)parseDefaultResult;
- (id)ruleOfCountryCode:(id)arg1;
- (id)ruleOfFinal;
- (id)ruleOfDomain:(id)arg1;
- (_Bool)isGloablDirect;
- (_Bool)isGloablProxy;
- (long long)routingType;
- (void)setupIpsetWithCidrs:(id)arg1;
- (void)reloadRuleFile;
- (void)reload;
- (void)reloadIfNeed;
- (void)dealloc;
- (id)initWithName:(id)arg1;
- (id)init;

@end

