//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSFileHandle, NSURL;
@protocol OS_dispatch_source;

@interface DLWServerNotify : NSObject
{
    _Bool _keepMonitoringFile;
    int _fileDescriptor;
    NSObject<OS_dispatch_source> *_source;
    NSFileHandle *_fileHandle;
    NSURL *_fileURL;
    CDUnknownBlockType _notifyBlock;
}

+ (id)sharedInstance;
@property(copy, nonatomic) CDUnknownBlockType notifyBlock; // @synthesize notifyBlock=_notifyBlock;
@property(retain, nonatomic) NSURL *fileURL; // @synthesize fileURL=_fileURL;
@property(nonatomic) _Bool keepMonitoringFile; // @synthesize keepMonitoringFile=_keepMonitoringFile;
@property(retain, nonatomic) NSFileHandle *fileHandle; // @synthesize fileHandle=_fileHandle;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *source; // @synthesize source=_source;
@property(nonatomic) int fileDescriptor; // @synthesize fileDescriptor=_fileDescriptor;
- (void).cxx_destruct;
- (void)dealloc;
- (void)notifyIfNeeded;
- (void)notify;
- (void)notifyWithBlock:(CDUnknownBlockType)arg1;
- (void)sendServer:(id)arg1;
- (id)init;

@end

