//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface DLWStatisticsItem : NSObject
{
    unsigned long long _proxyReqs;
    unsigned long long _proxyInBytes;
    unsigned long long _proxyOutBytes;
    unsigned long long _rejectReqs;
    unsigned long long _directReqs;
    unsigned long long _directInBytes;
    unsigned long long _directOutBytes;
    double _startTime;
    double _endTime;
}

@property(nonatomic) double endTime; // @synthesize endTime=_endTime;
@property(nonatomic) double startTime; // @synthesize startTime=_startTime;
@property(nonatomic) unsigned long long directOutBytes; // @synthesize directOutBytes=_directOutBytes;
@property(nonatomic) unsigned long long directInBytes; // @synthesize directInBytes=_directInBytes;
@property(nonatomic) unsigned long long directReqs; // @synthesize directReqs=_directReqs;
@property(nonatomic) unsigned long long rejectReqs; // @synthesize rejectReqs=_rejectReqs;
@property(nonatomic) unsigned long long proxyOutBytes; // @synthesize proxyOutBytes=_proxyOutBytes;
@property(nonatomic) unsigned long long proxyInBytes; // @synthesize proxyInBytes=_proxyInBytes;
@property(nonatomic) unsigned long long proxyReqs; // @synthesize proxyReqs=_proxyReqs;
- (unsigned long long)allBytes;
- (void)reset;
- (void)addFromDict:(id)arg1;

@end

