//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DLWViewController.h"

@interface DLWSpeedTestViewController : DLWViewController
{
}

- (void)showEditViewControllerWithSender:(id)arg1;
- (void)showUseViewControllerWithSender:(id)arg1;
- (void)showSheetViewControllerWithSender:(id)arg1;
- (void)addGroupSectionWithGroup:(id)arg1 atSection:(id)arg2;
- (void)setupTableViewManager;
- (void)viewDidLoad;
- (id)init;

@end

