//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface DLWServerGroup : NSObject
{
    int _weight;
    NSString *_name;
    NSArray *_servers;
}

@property(retain, nonatomic) NSArray *servers; // @synthesize servers=_servers;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) int weight; // @synthesize weight=_weight;
- (void).cxx_destruct;

@end

