//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSMutableSet, NSOperationQueue;
@protocol OS_dispatch_semaphore, OS_dispatch_source;

@interface DLWServerManager : NSObject
{
    _Bool _silentOnce;
    _Bool _isAppExtension;
    CDUnknownBlockType _block;
    NSOperationQueue *_queue;
    NSMutableSet *_deletedServerIds;
    NSObject<OS_dispatch_semaphore> *_lock;
    NSObject<OS_dispatch_source> *_source;
    NSMutableArray *_servers;
}

+ (id)sharedManager;
@property(nonatomic) _Bool isAppExtension; // @synthesize isAppExtension=_isAppExtension;
@property(retain, nonatomic) NSMutableArray *servers; // @synthesize servers=_servers;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *source; // @synthesize source=_source;
@property(retain, nonatomic) NSObject<OS_dispatch_semaphore> *lock; // @synthesize lock=_lock;
@property(retain, nonatomic) NSMutableSet *deletedServerIds; // @synthesize deletedServerIds=_deletedServerIds;
@property(retain, nonatomic) NSOperationQueue *queue; // @synthesize queue=_queue;
@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
@property(nonatomic) _Bool silentOnce; // @synthesize silentOnce=_silentOnce;
- (void).cxx_destruct;
- (void)dealloc;
- (void)notifyWithBlock:(CDUnknownBlockType)arg1;
- (void)readWithBlock:(CDUnknownBlockType)arg1;
- (id)resourcePath;
- (void)close;
- (void)silentSynchronize;
- (void)synchronize;
- (void)synchronizeFileSilent:(_Bool)arg1;
- (void)deleteAll;
- (void)removeServer:(id)arg1;
- (void)addServers:(id)arg1;
- (void)addServer:(id)arg1;
- (void)moveServerIndex:(long long)arg1 destinationIndex:(long long)arg2;
- (void)moveServer:(id)arg1 destinationIndex:(long long)arg2;
- (void)selectServer:(id)arg1;
- (id)serversWithIds:(id)arg1;
- (id)serversWithNames:(id)arg1;
- (id)serverWithId:(id)arg1;
- (id)serverWithName:(id)arg1;
- (id)serverNames;
- (id)currentServer;
- (id)current;
- (void)removeServersWithData:(id)arg1;
- (void)enumerateServerUsingBlock:(CDUnknownBlockType)arg1;
- (id)lookupServerWithDictionary:(id)arg1;
- (id)all;
- (unsigned long long)count;
- (void)sortServers;
- (void)reload;
- (void)notify;
- (_Bool)checkAppExtension;
- (id)init;
- (id)filteredArrayUsingPredicate:(id)arg1;
- (id)subscribes;
- (id)groupServers;
- (id)widgetServers;
- (id)cloudJSONServers;
- (id)cloudServers;
- (id)sortedServers;
- (id)hosts;
- (void)startMigraine;
- (void)cloudSynchronizeWithCompletion:(CDUnknownBlockType)arg1;
- (void)startCloudSynchronize;
- (void)performSynchronizeNotification;

@end

