//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DLWViewController.h"

@interface DLWTodayServersViewController : DLWViewController
{
}

- (_Bool)tableView:(id)arg1 shouldIndentWhileEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willLoadCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)saveServers;
- (void)setupTableViewManager;
- (void)viewDidLoad;
- (id)init;

@end

