//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol OS_dispatch_queue;

@interface DLWTrieRule : NSObject
{
    struct trie_ctx_s *trie;
    void *IsOnQueueOrTargetQueueKey;
    long long _ipRules;
    long long _domainRules;
    long long _geoipAll;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(nonatomic) long long geoipAll; // @synthesize geoipAll=_geoipAll;
@property(nonatomic) long long domainRules; // @synthesize domainRules=_domainRules;
@property(nonatomic) long long ipRules; // @synthesize ipRules=_ipRules;
- (void).cxx_destruct;
- (void)close;
- (void)dealloc;
- (_Bool)save:(id)arg1;
- (_Bool)store:(id)arg1 value:(unsigned int)arg2;
- (long long)retrieve:(id)arg1;
- (long long)lookup:(id)arg1 range:(struct _NSRange *)arg2;
- (_Bool)loadAtPath:(id)arg1;
- (id)initEmptyTrieRule;
- (id)init;

@end

