//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIColor;

@interface DLWWifiView : UIView
{
    _Bool _animating;
    UIColor *_tintColor;
    double _size;
}

@property(readonly, nonatomic) _Bool animating; // @synthesize animating=_animating;
@property(nonatomic) double size; // @synthesize size=_size;
@property(retain, nonatomic) UIColor *tintColor; // @synthesize tintColor=_tintColor;
- (void).cxx_destruct;
- (void)setupAnimationInLayer:(id)arg1 withSize:(struct CGSize)arg2 tintColor:(id)arg3;
- (void)stopAnimating;
- (void)startAnimating;

@end

