//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GCDWebServerDelegate-Protocol.h"

@class DLWWebUploader, NSString;

@protocol DLWWebUploaderDelegate <GCDWebServerDelegate>

@optional
- (void)webUploader:(DLWWebUploader *)arg1 didDeleteItemAtPath:(NSString *)arg2;
- (void)webUploader:(DLWWebUploader *)arg1 didUploadFileAtPath:(NSString *)arg2;
- (void)webUploader:(DLWWebUploader *)arg1 didDownloadFileAtPath:(NSString *)arg2;
@end

