//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString;

@interface ICACloudFile : NSObject
{
    NSString *path;
    NSString *name;
    NSDictionary *fileAttributes;
}

@property(retain) NSDictionary *fileAttributes; // @synthesize fileAttributes;
@property(copy) NSString *name; // @synthesize name;
@property(copy) NSString *path; // @synthesize path;
- (void).cxx_destruct;

@end

