//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSFileManager, NSMetadataQuery, NSOperationQueue, NSString, NSURL;
@protocol NSObject><NSCopying><NSCoding, OS_dispatch_queue;

@interface ICACloud : NSObject
{
    NSFileManager *fileManager;
    NSURL *rootDirectoryURL;
    NSMetadataQuery *metadataQuery;
    NSOperationQueue *operationQueue;
    NSString *ubiquityContainerIdentifier;
    NSObject<OS_dispatch_queue> *timeOutQueue;
    id ubiquityIdentityObserver;
    NSString *rootDirectoryPath;
}

@property(readonly, nonatomic) NSString *rootDirectoryPath; // @synthesize rootDirectoryPath;
- (void).cxx_destruct;
- (void)downloadFromPath:(id)arg1 toLocalFile:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)downloadDataFromPath:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)uploadLocalFile:(id)arg1 toPath:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)uploadData:(id)arg1 toPath:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)temporaryDirectory;
- (void)removeItemAtPath:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)createDirectoryAtPath:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)contentsOfDirectoryAtPath:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)fileExistsAtPath:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)notConnectedError;
- (id)specializedErrorForCocoaError:(id)arg1;
- (void)resolveConflictsForMetadataItem:(id)arg1;
- (void)initiateDownloads:(id)arg1;
- (void)stopMonitoring;
- (void)startMonitoringMetadata;
- (void)connect;
@property(readonly, nonatomic) _Bool isConnected;
- (void)addUbiquityContainerNotificationObservers;
- (void)removeUbiquityContainerNotificationObservers;
- (id)fullPathForPath:(id)arg1;
- (void)dispatchCompletion:(CDUnknownBlockType)arg1 withError:(id)arg2;
- (void)setupRootDirectory:(CDUnknownBlockType)arg1;
- (void)performInitialPreparation:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) id <NSObject><NSCopying><NSCoding> identityToken;
- (void)dealloc;
- (id)init;
- (id)initWithUbiquityContainerIdentifier:(id)arg1;
- (id)initWithUbiquityContainerIdentifier:(id)arg1 rootDirectoryPath:(id)arg2;

@end

