//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NetworkExtension/NETunnelProviderManager.h>

@interface NETunnelProviderManager (Additions)
- (void)disconnectWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)connectWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)saveWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)toggleWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)session;
@end

