//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSDictionary.h>

@interface NSDictionary (Rubyfy)
- (_Bool)hasKey:(id)arg1;
- (id)map:(CDUnknownBlockType)arg1;
- (void)eachValue:(CDUnknownBlockType)arg1;
- (void)eachKey:(CDUnknownBlockType)arg1;
- (void)each:(CDUnknownBlockType)arg1;
@end

