//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSNumber.h>

@interface NSNumber (ObjectiveSugar)
- (id)fromNow;
- (id)until:(id)arg1;
- (id)since:(id)arg1;
- (id)ago:(id)arg1;
- (id)ago;
- (id)years;
- (id)year;
- (id)months;
- (id)month;
- (id)fortnights;
- (id)fortnight;
- (id)weeks;
- (id)week;
- (id)days;
- (id)day;
- (id)hours;
- (id)hour;
- (id)minutes;
- (id)minute;
- (id)seconds;
- (id)second;
- (void)downto:(int)arg1 do:(CDUnknownBlockType)arg2;
- (void)upto:(int)arg1 do:(CDUnknownBlockType)arg2;
- (void)timesWithIndex:(CDUnknownBlockType)arg1;
- (void)times:(CDUnknownBlockType)arg1;
@end

