//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface NSObject (JGMethodDeSwizzler)
+ (_Bool)deswizzleAllMethods;
+ (_Bool)deswizzleAllInstanceMethods;
+ (_Bool)deswizzleAllClassMethods;
+ (_Bool)deswizzleInstanceMethod:(SEL)arg1;
+ (_Bool)deswizzleClassMethod:(SEL)arg1;
@end

