//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (DLWURLManager)
- (id)dlw_partitionByString:(id)arg1;
- (id)dlw_base64Encode;
- (id)dlw_base64Decode;
- (id)dlw_base64Escape;
- (id)dlw_base64Unescape;
- (id)dlw_urlDecode;
- (id)dlw_urlDecodeIfNeeded;
- (id)dlw_urlEncode;
@end

