//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface PNLineChartDataItem : NSObject
{
    double _y;
    double _rawY;
}

+ (id)dataItemWithY:(double)arg1 andRawY:(double)arg2;
+ (id)dataItemWithY:(double)arg1;
@property double rawY; // @synthesize rawY=_rawY;
@property double y; // @synthesize y=_y;
- (id)initWithY:(double)arg1 andRawY:(double)arg2;

@end

