//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PNGenericChart.h"

@class CABasicAnimation, NSArray, NSMutableArray, NSString, UIColor, UIFont;
@protocol PNChartDelegate;

@interface PNLineChart : PNGenericChart
{
    _Bool _showLabel;
    _Bool _showGenYLabels;
    _Bool _showYGridLines;
    _Bool _thousandsSeparator;
    _Bool _showCoordinateAxis;
    _Bool _showSmoothLines;
    CABasicAnimation *_pathAnimation;
    id <PNChartDelegate> _delegate;
    NSArray *_xLabels;
    NSArray *_yLabels;
    NSArray *_chartData;
    NSMutableArray *_pathPoints;
    NSMutableArray *_xChartLabels;
    NSMutableArray *_yChartLabels;
    double _xLabelWidth;
    UIFont *_xLabelFont;
    UIColor *_xLabelColor;
    double _yValueMax;
    double _yFixedValueMax;
    double _yFixedValueMin;
    double _yValueMin;
    long long _yLabelNum;
    double _yLabelHeight;
    UIFont *_yLabelFont;
    UIColor *_yLabelColor;
    double _chartCavanHeight;
    double _chartCavanWidth;
    UIColor *_yGridLinesColor;
    double _chartMarginLeft;
    double _chartMarginRight;
    double _chartMarginTop;
    double _chartMarginBottom;
    UIColor *_axisColor;
    double _axisWidth;
    NSString *_xUnit;
    NSString *_yUnit;
    NSString *_yLabelFormat;
    CDUnknownBlockType _yLabelBlockFormatter;
    NSMutableArray *_chartLineArray;
    NSMutableArray *_chartPointArray;
    NSMutableArray *_chartPath;
    NSMutableArray *_pointPath;
    NSMutableArray *_endPointsOfPath;
    NSMutableArray *_gradeStringPaths;
}

+ (struct CGPoint)controlPointBetweenPoint1:(struct CGPoint)arg1 andPoint2:(struct CGPoint)arg2;
+ (struct CGPoint)midPointBetweenPoint1:(struct CGPoint)arg1 andPoint2:(struct CGPoint)arg2;
+ (struct CGSize)sizeOfString:(id)arg1 withWidth:(float)arg2 font:(id)arg3;
@property(retain, nonatomic) NSMutableArray *gradeStringPaths; // @synthesize gradeStringPaths=_gradeStringPaths;
@property(retain, nonatomic) NSMutableArray *endPointsOfPath; // @synthesize endPointsOfPath=_endPointsOfPath;
@property(retain, nonatomic) NSMutableArray *pointPath; // @synthesize pointPath=_pointPath;
@property(retain, nonatomic) NSMutableArray *chartPath; // @synthesize chartPath=_chartPath;
@property(retain, nonatomic) NSMutableArray *chartPointArray; // @synthesize chartPointArray=_chartPointArray;
@property(retain, nonatomic) NSMutableArray *chartLineArray; // @synthesize chartLineArray=_chartLineArray;
@property(nonatomic) _Bool showSmoothLines; // @synthesize showSmoothLines=_showSmoothLines;
@property(copy, nonatomic) CDUnknownBlockType yLabelBlockFormatter; // @synthesize yLabelBlockFormatter=_yLabelBlockFormatter;
@property(retain, nonatomic) NSString *yLabelFormat; // @synthesize yLabelFormat=_yLabelFormat;
@property(retain, nonatomic) NSString *yUnit; // @synthesize yUnit=_yUnit;
@property(retain, nonatomic) NSString *xUnit; // @synthesize xUnit=_xUnit;
@property(nonatomic) double axisWidth; // @synthesize axisWidth=_axisWidth;
@property(retain, nonatomic) UIColor *axisColor; // @synthesize axisColor=_axisColor;
@property(nonatomic, getter=isShowCoordinateAxis) _Bool showCoordinateAxis; // @synthesize showCoordinateAxis=_showCoordinateAxis;
@property(nonatomic) double chartMarginBottom; // @synthesize chartMarginBottom=_chartMarginBottom;
@property(nonatomic) double chartMarginTop; // @synthesize chartMarginTop=_chartMarginTop;
@property(nonatomic) double chartMarginRight; // @synthesize chartMarginRight=_chartMarginRight;
@property(nonatomic) double chartMarginLeft; // @synthesize chartMarginLeft=_chartMarginLeft;
@property(nonatomic) _Bool thousandsSeparator; // @synthesize thousandsSeparator=_thousandsSeparator;
@property(retain, nonatomic) UIColor *yGridLinesColor; // @synthesize yGridLinesColor=_yGridLinesColor;
@property(nonatomic) _Bool showYGridLines; // @synthesize showYGridLines=_showYGridLines;
@property(nonatomic) _Bool showGenYLabels; // @synthesize showGenYLabels=_showGenYLabels;
@property(nonatomic) _Bool showLabel; // @synthesize showLabel=_showLabel;
@property(nonatomic) double chartCavanWidth; // @synthesize chartCavanWidth=_chartCavanWidth;
@property(nonatomic) double chartCavanHeight; // @synthesize chartCavanHeight=_chartCavanHeight;
@property(retain, nonatomic) UIColor *yLabelColor; // @synthesize yLabelColor=_yLabelColor;
@property(retain, nonatomic) UIFont *yLabelFont; // @synthesize yLabelFont=_yLabelFont;
@property(nonatomic) double yLabelHeight; // @synthesize yLabelHeight=_yLabelHeight;
@property(nonatomic) long long yLabelNum; // @synthesize yLabelNum=_yLabelNum;
@property(nonatomic) double yValueMin; // @synthesize yValueMin=_yValueMin;
@property(nonatomic) double yFixedValueMin; // @synthesize yFixedValueMin=_yFixedValueMin;
@property(nonatomic) double yFixedValueMax; // @synthesize yFixedValueMax=_yFixedValueMax;
@property(nonatomic) double yValueMax; // @synthesize yValueMax=_yValueMax;
@property(retain, nonatomic) UIColor *xLabelColor; // @synthesize xLabelColor=_xLabelColor;
@property(retain, nonatomic) UIFont *xLabelFont; // @synthesize xLabelFont=_xLabelFont;
@property(nonatomic) double xLabelWidth; // @synthesize xLabelWidth=_xLabelWidth;
@property(retain, nonatomic) NSMutableArray *yChartLabels; // @synthesize yChartLabels=_yChartLabels;
@property(retain, nonatomic) NSMutableArray *xChartLabels; // @synthesize xChartLabels=_xChartLabels;
@property(retain, nonatomic) NSMutableArray *pathPoints; // @synthesize pathPoints=_pathPoints;
@property(retain, nonatomic) NSArray *chartData; // @synthesize chartData=_chartData;
@property(retain, nonatomic) NSArray *yLabels; // @synthesize yLabels=_yLabels;
@property(retain, nonatomic) NSArray *xLabels; // @synthesize xLabels=_xLabels;
@property(nonatomic) __weak id <PNChartDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) CABasicAnimation *pathAnimation; // @synthesize pathAnimation=_pathAnimation;
- (void).cxx_destruct;
- (id)fadeAnimation;
- (id)createPointLabelFor:(double)arg1 pointCenter:(struct CGPoint)arg2 width:(double)arg3 withChartData:(id)arg4;
- (id)drawInflexion:(double)arg1 center:(struct CGPoint)arg2 strokeWidth:(double)arg3 inflexionStyle:(unsigned long long)arg4 andColor:(id)arg5 andAlpha:(double)arg6;
- (id)getLegendWithMaxWidth:(double)arg1;
- (id)formatYLabel:(double)arg1;
- (void)drawTextInContext:(struct CGContext *)arg1 text:(id)arg2 inRect:(struct CGRect)arg3 font:(id)arg4;
- (void)setupDefaultValues;
- (void)drawRect:(struct CGRect)arg1;
- (void)updateChartData:(id)arg1;
- (void)prepareYLabelsWithData:(id)arg1;
- (void)calculateChartPath:(id)arg1 andPointsPath:(id)arg2 andPathKeyPoints:(id)arg3 andPathStartEndPoints:(id)arg4;
- (void)strokeChart;
- (void)touchKeyPoint:(id)arg1 withEvent:(id)arg2;
- (void)touchPoint:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)setCustomStyleForYLabel:(id)arg1;
- (void)setCustomStyleForXLabel:(id)arg1;
- (void)setXLabels:(id)arg1 withWidth:(double)arg2;
- (double)computeEqualWidthForXLabels:(id)arg1;
- (void)setYLabels:(id)arg1 withHeight:(double)arg2;
- (void)setYLabels;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

