//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIColor;

@interface PNPieChartDataItem : NSObject
{
    double _value;
    UIColor *_color;
    NSString *_textDescription;
}

+ (id)dataItemWithValue:(double)arg1 color:(id)arg2 description:(id)arg3;
+ (id)dataItemWithValue:(double)arg1 color:(id)arg2;
@property(retain, nonatomic) NSString *textDescription; // @synthesize textDescription=_textDescription;
@property(retain, nonatomic) UIColor *color; // @synthesize color=_color;
@property(nonatomic) double value; // @synthesize value=_value;
- (void).cxx_destruct;

@end

