//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PNGenericChart.h"

@class CAShapeLayer, NSArray, NSMutableArray, NSString, UIColor, UIFont;
@protocol PNChartDelegate;

@interface PNScatterChart : PNGenericChart
{
    _Bool _showCoordinateAxis;
    _Bool _showLabel;
    _Bool _isForUpdate;
    int _AxisX_partNumber;
    int _AxisY_partNumber;
    id <PNChartDelegate> _delegate;
    NSArray *_chartData;
    UIColor *_axisColor;
    double _axisWidth;
    NSString *_xLabelFormat;
    NSString *_yLabelFormat;
    UIFont *_descriptionTextFont;
    UIColor *_descriptionTextColor;
    UIColor *_descriptionTextShadowColor;
    double _duration;
    double _AxisX_minValue;
    double _AxisX_maxValue;
    double _AxisY_minValue;
    double _AxisY_maxValue;
    CAShapeLayer *_pathLayer;
    NSMutableArray *_verticalLineLayer;
    NSMutableArray *_horizentalLinepathLayer;
    double _vectorX_Steps;
    double _vectorY_Steps;
    double _vectorX_Size;
    double _vectorY_Size;
    NSMutableArray *_axisX_labels;
    NSMutableArray *_axisY_labels;
    double _AxisX_step;
    double _AxisY_step;
    double _AxisX_Margin;
    double _AxisY_Margin;
    struct CGSize _descriptionTextShadowOffset;
    struct CGPoint _startPoint;
    struct CGPoint _startPointVectorX;
    struct CGPoint _endPointVecotrX;
    struct CGPoint _startPointVectorY;
    struct CGPoint _endPointVecotrY;
}

@property(nonatomic) _Bool isForUpdate; // @synthesize isForUpdate=_isForUpdate;
@property(nonatomic) double AxisY_Margin; // @synthesize AxisY_Margin=_AxisY_Margin;
@property(nonatomic) double AxisX_Margin; // @synthesize AxisX_Margin=_AxisX_Margin;
@property(nonatomic) double AxisY_step; // @synthesize AxisY_step=_AxisY_step;
@property(nonatomic) double AxisX_step; // @synthesize AxisX_step=_AxisX_step;
@property(nonatomic) int AxisY_partNumber; // @synthesize AxisY_partNumber=_AxisY_partNumber;
@property(nonatomic) int AxisX_partNumber; // @synthesize AxisX_partNumber=_AxisX_partNumber;
@property(retain, nonatomic) NSMutableArray *axisY_labels; // @synthesize axisY_labels=_axisY_labels;
@property(retain, nonatomic) NSMutableArray *axisX_labels; // @synthesize axisX_labels=_axisX_labels;
@property(nonatomic) double vectorY_Size; // @synthesize vectorY_Size=_vectorY_Size;
@property(nonatomic) double vectorX_Size; // @synthesize vectorX_Size=_vectorX_Size;
@property(nonatomic) double vectorY_Steps; // @synthesize vectorY_Steps=_vectorY_Steps;
@property(nonatomic) double vectorX_Steps; // @synthesize vectorX_Steps=_vectorX_Steps;
@property(nonatomic) struct CGPoint endPointVecotrY; // @synthesize endPointVecotrY=_endPointVecotrY;
@property(nonatomic) struct CGPoint startPointVectorY; // @synthesize startPointVectorY=_startPointVectorY;
@property(nonatomic) struct CGPoint endPointVecotrX; // @synthesize endPointVecotrX=_endPointVecotrX;
@property(nonatomic) struct CGPoint startPointVectorX; // @synthesize startPointVectorX=_startPointVectorX;
@property(nonatomic) struct CGPoint startPoint; // @synthesize startPoint=_startPoint;
@property(nonatomic) __weak NSMutableArray *horizentalLinepathLayer; // @synthesize horizentalLinepathLayer=_horizentalLinepathLayer;
@property(nonatomic) __weak NSMutableArray *verticalLineLayer; // @synthesize verticalLineLayer=_verticalLineLayer;
@property(nonatomic) __weak CAShapeLayer *pathLayer; // @synthesize pathLayer=_pathLayer;
@property(nonatomic) double AxisY_maxValue; // @synthesize AxisY_maxValue=_AxisY_maxValue;
@property(nonatomic) double AxisY_minValue; // @synthesize AxisY_minValue=_AxisY_minValue;
@property(nonatomic) double AxisX_maxValue; // @synthesize AxisX_maxValue=_AxisX_maxValue;
@property(nonatomic) double AxisX_minValue; // @synthesize AxisX_minValue=_AxisX_minValue;
@property(nonatomic) double duration; // @synthesize duration=_duration;
@property(nonatomic) struct CGSize descriptionTextShadowOffset; // @synthesize descriptionTextShadowOffset=_descriptionTextShadowOffset;
@property(retain, nonatomic) UIColor *descriptionTextShadowColor; // @synthesize descriptionTextShadowColor=_descriptionTextShadowColor;
@property(retain, nonatomic) UIColor *descriptionTextColor; // @synthesize descriptionTextColor=_descriptionTextColor;
@property(retain, nonatomic) UIFont *descriptionTextFont; // @synthesize descriptionTextFont=_descriptionTextFont;
@property(nonatomic) _Bool showLabel; // @synthesize showLabel=_showLabel;
@property(retain, nonatomic) NSString *yLabelFormat; // @synthesize yLabelFormat=_yLabelFormat;
@property(retain, nonatomic) NSString *xLabelFormat; // @synthesize xLabelFormat=_xLabelFormat;
@property(nonatomic) double axisWidth; // @synthesize axisWidth=_axisWidth;
@property(retain, nonatomic) UIColor *axisColor; // @synthesize axisColor=_axisColor;
@property(nonatomic, getter=isShowCoordinateAxis) _Bool showCoordinateAxis; // @synthesize showCoordinateAxis=_showCoordinateAxis;
@property(retain, nonatomic) NSArray *chartData; // @synthesize chartData=_chartData;
@property(retain, nonatomic) id <PNChartDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)addStrokeEndAnimationIfNeededToLayer:(id)arg1;
- (void)drawLineFromPoint:(struct CGPoint)arg1 ToPoint:(struct CGPoint)arg2 WithLineWith:(double)arg3 AndWithColor:(id)arg4;
- (id)drawingPointsForChartData:(id)arg1 AndWithX:(double)arg2 AndWithY:(double)arg3;
- (void)drawRect:(struct CGRect)arg1;
- (void)updateChartData:(id)arg1;
- (double)mappingIsForAxisX:(_Bool)arg1 WithValue:(double)arg2;
- (void)addAnimationIfNeeded;
- (void)showXLabel:(id)arg1 InPosition:(struct CGPoint)arg2;
- (void)vectorYSetup;
- (void)vectorXSetup;
- (void)setAxisYLabel:(id)arg1;
- (void)setAxisXLabel:(id)arg1;
- (id)getAxisMinMax:(id)arg1;
- (void)setAxisYWithMinimumValue:(double)arg1 andMaxValue:(double)arg2 toTicks:(int)arg3;
- (void)setAxisXWithMinimumValue:(double)arg1 andMaxValue:(double)arg2 toTicks:(int)arg3;
- (void)setupDefaultValues;
- (void)setup;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

