//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface PNScatterChartDataItem : NSObject
{
    double _x;
    double _y;
}

+ (id)dataItemWithX:(double)arg1 AndWithY:(double)arg2;
@property double y; // @synthesize y=_y;
@property double x; // @synthesize x=_x;
- (id)initWithX:(double)arg1 AndWithY:(double)arg2;

@end

