//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UIColor;

@interface PNScatterChartData : NSObject
{
    UIColor *_fillColor;
    UIColor *_strokeColor;
    unsigned long long _itemCount;
    CDUnknownBlockType _getData;
    unsigned long long _inflexionPointStyle;
    double _size;
}

@property(nonatomic) double size; // @synthesize size=_size;
@property(nonatomic) unsigned long long inflexionPointStyle; // @synthesize inflexionPointStyle=_inflexionPointStyle;
@property(copy) CDUnknownBlockType getData; // @synthesize getData=_getData;
@property unsigned long long itemCount; // @synthesize itemCount=_itemCount;
@property(retain) UIColor *strokeColor; // @synthesize strokeColor=_strokeColor;
@property(retain) UIColor *fillColor; // @synthesize fillColor=_fillColor;
- (void).cxx_destruct;
- (void)setupDefaultValues;
- (id)init;

@end

