//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class RDVTabBarController, UIViewController;

@protocol RDVTabBarControllerDelegate <NSObject>

@optional
- (void)tabBarController:(RDVTabBarController *)arg1 didSelectViewController:(UIViewController *)arg2;
- (_Bool)tabBarController:(RDVTabBarController *)arg1 shouldSelectViewController:(UIViewController *)arg2;
@end

