//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class RDVTabBar;

@protocol RDVTabBarDelegate <NSObject>
- (void)tabBar:(RDVTabBar *)arg1 didSelectItemAtIndex:(long long)arg2;
- (_Bool)tabBar:(RDVTabBar *)arg1 shouldSelectItemAtIndex:(long long)arg2;
@end

