//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RETableViewItem.h"

@class NSString, UIImage;

@interface RECreditCardItem : RETableViewItem
{
    _Bool _cvvRequired;
    UIImage *_expiredRibbonImage;
    NSString *_number;
    NSString *_expirationDate;
    NSString *_cvv;
    unsigned long long _creditCardType;
    long long _keyboardAppearance;
}

+ (id)item;
+ (id)itemWithNumber:(id)arg1 expirationString:(id)arg2 cvv:(id)arg3;
+ (id)itemWithNumber:(id)arg1 expirationDate:(id)arg2 cvv:(id)arg3;
@property(nonatomic) long long keyboardAppearance; // @synthesize keyboardAppearance=_keyboardAppearance;
@property(nonatomic) _Bool cvvRequired; // @synthesize cvvRequired=_cvvRequired;
@property(nonatomic) unsigned long long creditCardType; // @synthesize creditCardType=_creditCardType;
@property(copy, nonatomic) NSString *cvv; // @synthesize cvv=_cvv;
@property(copy, nonatomic) NSString *expirationDate; // @synthesize expirationDate=_expirationDate;
@property(copy, nonatomic) NSString *number; // @synthesize number=_number;
@property(retain, nonatomic) UIImage *expiredRibbonImage; // @synthesize expiredRibbonImage=_expiredRibbonImage;
- (void).cxx_destruct;
- (id)errors;
- (id)initWithNumber:(id)arg1 expirationDate:(id)arg2 cvv:(id)arg3;

@end

