//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RETableViewItem.h"

@class NSCalendar, NSDate, NSLocale, NSString, NSTimeZone, REInlineDatePickerItem;

@interface REDateTimeItem : RETableViewItem
{
    _Bool _inlineDatePicker;
    NSDate *_value;
    NSDate *_pickerStartDate;
    NSString *_placeholder;
    NSString *_format;
    long long _datePickerMode;
    NSLocale *_locale;
    NSCalendar *_calendar;
    NSTimeZone *_timeZone;
    NSDate *_minimumDate;
    NSDate *_maximumDate;
    long long _minuteInterval;
    CDUnknownBlockType _onChange;
    REInlineDatePickerItem *_inlinePickerItem;
}

+ (id)itemWithTitle:(id)arg1 value:(id)arg2 placeholder:(id)arg3 format:(id)arg4 datePickerMode:(long long)arg5;
@property(retain, nonatomic) REInlineDatePickerItem *inlinePickerItem; // @synthesize inlinePickerItem=_inlinePickerItem;
@property(nonatomic) _Bool inlineDatePicker; // @synthesize inlineDatePicker=_inlineDatePicker;
@property(copy, nonatomic) CDUnknownBlockType onChange; // @synthesize onChange=_onChange;
@property(nonatomic) long long minuteInterval; // @synthesize minuteInterval=_minuteInterval;
@property(retain, nonatomic) NSDate *maximumDate; // @synthesize maximumDate=_maximumDate;
@property(retain, nonatomic) NSDate *minimumDate; // @synthesize minimumDate=_minimumDate;
@property(retain, nonatomic) NSTimeZone *timeZone; // @synthesize timeZone=_timeZone;
@property(copy, nonatomic) NSCalendar *calendar; // @synthesize calendar=_calendar;
@property(retain, nonatomic) NSLocale *locale; // @synthesize locale=_locale;
@property(nonatomic) long long datePickerMode; // @synthesize datePickerMode=_datePickerMode;
@property(retain, nonatomic) NSString *format; // @synthesize format=_format;
@property(copy, nonatomic) NSString *placeholder; // @synthesize placeholder=_placeholder;
@property(retain, nonatomic) NSDate *pickerStartDate; // @synthesize pickerStartDate=_pickerStartDate;
@property(retain, nonatomic) NSDate *value; // @synthesize value=_value;
- (void).cxx_destruct;
- (id)errors;
- (id)initWithTitle:(id)arg1 value:(id)arg2 placeholder:(id)arg3 format:(id)arg4 datePickerMode:(long long)arg5;

@end

