//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RETableViewItem.h"

@interface REFloatItem : RETableViewItem
{
    float _value;
    double _sliderWidth;
    CDUnknownBlockType _sliderValueChangeHandler;
}

+ (id)itemWithTitle:(id)arg1 value:(float)arg2 sliderValueChangeHandler:(CDUnknownBlockType)arg3;
+ (id)itemWithTitle:(id)arg1 value:(float)arg2;
@property(copy, nonatomic) CDUnknownBlockType sliderValueChangeHandler; // @synthesize sliderValueChangeHandler=_sliderValueChangeHandler;
@property(nonatomic) double sliderWidth; // @synthesize sliderWidth=_sliderWidth;
@property(nonatomic) float value; // @synthesize value=_value;
- (void).cxx_destruct;
- (id)errors;
- (id)initWithTitle:(id)arg1 value:(float)arg2 sliderValueChangeHandler:(CDUnknownBlockType)arg3;
- (id)initWithTitle:(id)arg1 value:(float)arg2;

@end

