//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RETextItem.h"

@class NSString;

@interface RENumberItem : RETextItem
{
    NSString *_format;
}

+ (id)itemWithTitle:(id)arg1 value:(id)arg2 placeholder:(id)arg3 format:(id)arg4;
@property(copy, nonatomic) NSString *format; // @synthesize format=_format;
- (void).cxx_destruct;
- (id)initWithTitle:(id)arg1 value:(id)arg2 placeholder:(id)arg3 format:(id)arg4;

@end

