//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, NSString, RETableViewCellStyle, RETableViewManager, UIView;

@interface RETableViewSection : NSObject
{
    NSString *_headerTitle;
    NSString *_footerTitle;
    double _headerHeight;
    double _footerHeight;
    UIView *_headerView;
    UIView *_footerView;
    RETableViewManager *_tableViewManager;
    NSString *_indexTitle;
    double _cellTitlePadding;
    RETableViewCellStyle *_style;
    NSMutableArray *_mutableItems;
}

+ (id)sectionWithHeaderView:(id)arg1 footerView:(id)arg2;
+ (id)sectionWithHeaderView:(id)arg1;
+ (id)sectionWithHeaderTitle:(id)arg1 footerTitle:(id)arg2;
+ (id)sectionWithHeaderTitle:(id)arg1;
+ (id)section;
@property(retain, nonatomic) NSMutableArray *mutableItems; // @synthesize mutableItems=_mutableItems;
@property(retain, nonatomic) RETableViewCellStyle *style; // @synthesize style=_style;
@property(nonatomic) double cellTitlePadding; // @synthesize cellTitlePadding=_cellTitlePadding;
@property(copy, nonatomic) NSString *indexTitle; // @synthesize indexTitle=_indexTitle;
@property(nonatomic) __weak RETableViewManager *tableViewManager; // @synthesize tableViewManager=_tableViewManager;
@property(retain, nonatomic) UIView *footerView; // @synthesize footerView=_footerView;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(nonatomic) double footerHeight; // @synthesize footerHeight=_footerHeight;
@property(nonatomic) double headerHeight; // @synthesize headerHeight=_headerHeight;
@property(copy, nonatomic) NSString *footerTitle; // @synthesize footerTitle=_footerTitle;
@property(copy, nonatomic) NSString *headerTitle; // @synthesize headerTitle=_headerTitle;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSArray *errors;
- (void)reloadSectionWithAnimation:(long long)arg1;
- (void)sortItemsUsingSelector:(SEL)arg1;
- (void)sortItemsUsingFunction:(CDUnknownFunctionPointerType)arg1 context:(void *)arg2;
- (void)exchangeItemAtIndex:(unsigned long long)arg1 withItemAtIndex:(unsigned long long)arg2;
- (void)replaceItemsAtIndexes:(id)arg1 withItems:(id)arg2;
- (void)replaceItemsInRange:(struct _NSRange)arg1 withItemsFromArray:(id)arg2;
- (void)replaceItemsInRange:(struct _NSRange)arg1 withItemsFromArray:(id)arg2 range:(struct _NSRange)arg3;
- (void)replaceItemsWithItemsFromArray:(id)arg1;
- (void)replaceItemAtIndex:(unsigned long long)arg1 withItem:(id)arg2;
- (void)removeItemsAtIndexes:(id)arg1;
- (void)removeItemsInRange:(struct _NSRange)arg1;
- (void)removeItemsInArray:(id)arg1;
- (void)removeItemIdenticalTo:(id)arg1;
- (void)removeItemIdenticalTo:(id)arg1 inRange:(struct _NSRange)arg2;
- (void)removeAllItems;
- (void)removeItem:(id)arg1;
- (void)removeItemAtIndex:(unsigned long long)arg1;
- (void)removeLastItem;
- (void)removeItem:(id)arg1 inRange:(struct _NSRange)arg2;
- (void)insertItems:(id)arg1 atIndexes:(id)arg2;
- (void)insertItem:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)addItemsFromArray:(id)arg1;
- (void)addItem:(id)arg1;
@property(readonly, nonatomic) NSArray *items;
- (double)maximumTitleWidthWithFont:(id)arg1;
@property(readonly, nonatomic) unsigned long long index;
- (id)initWithHeaderView:(id)arg1 footerView:(id)arg2;
- (id)initWithHeaderView:(id)arg1;
- (id)initWithHeaderTitle:(id)arg1 footerTitle:(id)arg2;
- (id)initWithHeaderTitle:(id)arg1;
- (id)init;

@end

