//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RETableViewCell.h"

#import "UITextViewDelegate-Protocol.h"

@class NSString, RELongTextItem, REPlaceholderTextView;

@interface RETableViewLongTextCell : RETableViewCell <UITextViewDelegate>
{
    _Bool _enabled;
    RELongTextItem *_item;
    REPlaceholderTextView *_textView;
}

+ (_Bool)canFocusWithItem:(id)arg1;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(retain, nonatomic) REPlaceholderTextView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) RELongTextItem *item; // @synthesize item=_item;
- (void).cxx_destruct;
- (void)textViewDidChange:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (_Bool)textViewShouldEndEditing:(id)arg1;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)layoutSubviews;
- (id)responder;
- (void)cellWillAppear;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)cellDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

