//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSMutableDictionary, NSString, RETableViewCellStyle, UITableView;
@protocol RETableViewManagerDelegate;

@interface RETableViewManager : NSObject <UITableViewDelegate, UITableViewDataSource>
{
    UITableView *_tableView;
    id <RETableViewManagerDelegate> _delegate;
    NSMutableDictionary *_registeredClasses;
    RETableViewCellStyle *_style;
    NSMutableDictionary *_registeredXIBs;
    NSMutableArray *_mutableSections;
}

+ (void)initialize;
@property(retain, nonatomic) NSMutableArray *mutableSections; // @synthesize mutableSections=_mutableSections;
@property(retain, nonatomic) NSMutableDictionary *registeredXIBs; // @synthesize registeredXIBs=_registeredXIBs;
@property(retain, nonatomic) RETableViewCellStyle *style; // @synthesize style=_style;
@property(retain, nonatomic) NSMutableDictionary *registeredClasses; // @synthesize registeredClasses=_registeredClasses;
@property(nonatomic) id <RETableViewManagerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSArray *errors;
- (void)sortSectionsUsingSelector:(SEL)arg1;
- (void)sortSectionsUsingFunction:(CDUnknownFunctionPointerType)arg1 context:(void *)arg2;
- (void)exchangeSectionAtIndex:(unsigned long long)arg1 withSectionAtIndex:(unsigned long long)arg2;
- (void)replaceSectionsInRange:(struct _NSRange)arg1 withSectionsFromArray:(id)arg2;
- (void)replaceSectionsInRange:(struct _NSRange)arg1 withSectionsFromArray:(id)arg2 range:(struct _NSRange)arg3;
- (void)replaceSectionsAtIndexes:(id)arg1 withSections:(id)arg2;
- (void)replaceSectionsWithSectionsFromArray:(id)arg1;
- (void)replaceSectionAtIndex:(unsigned long long)arg1 withSection:(id)arg2;
- (void)removeSectionsAtIndexes:(id)arg1;
- (void)removeSectionAtIndex:(unsigned long long)arg1;
- (void)removeLastSection;
- (void)removeSection:(id)arg1 inRange:(struct _NSRange)arg2;
- (void)removeSectionsInRange:(struct _NSRange)arg1;
- (void)removeSectionsInArray:(id)arg1;
- (void)removeSectionIdenticalTo:(id)arg1;
- (void)removeSectionIdenticalTo:(id)arg1 inRange:(struct _NSRange)arg2;
- (void)removeAllSections;
- (void)removeSection:(id)arg1;
- (void)insertSections:(id)arg1 atIndexes:(id)arg2;
- (void)insertSection:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)addSectionsFromArray:(id)arg1;
- (void)addSection:(id)arg1;
- (void)scrollViewDidScrollToTop:(id)arg1;
- (_Bool)scrollViewShouldScrollToTop:(id)arg1;
- (void)scrollViewDidEndZooming:(id)arg1 withView:(id)arg2 atScale:(double)arg3;
- (void)scrollViewWillBeginZooming:(id)arg1 withView:(id)arg2;
- (id)viewForZoomingInScrollView:(id)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewWillBeginDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidZoom:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)tableView:(id)arg1 performAction:(SEL)arg2 forRowAtIndexPath:(id)arg3 withSender:(id)arg4;
- (_Bool)tableView:(id)arg1 canPerformAction:(SEL)arg2 forRowAtIndexPath:(id)arg3 withSender:(id)arg4;
- (_Bool)tableView:(id)arg1 shouldShowMenuForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 indentationLevelForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 targetIndexPathForMoveFromRowAtIndexPath:(id)arg2 toProposedIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didEndEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willBeginEditingRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 shouldIndentWhileEditingRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didDeselectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willDeselectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didUnhighlightRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didHighlightRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 accessoryButtonTappedForRowWithIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didEndDisplayingFooterView:(id)arg2 forSection:(long long)arg3;
- (void)tableView:(id)arg1 didEndDisplayingHeaderView:(id)arg2 forSection:(long long)arg3;
- (void)tableView:(id)arg1 didEndDisplayingCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 willDisplayFooterView:(id)arg2 forSection:(long long)arg3;
- (void)tableView:(id)arg1 willDisplayHeaderView:(id)arg2 forSection:(long long)arg3;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 editActionsForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3;
- (id)tableView:(id)arg1 titleForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (id)sectionIndexTitlesForTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
@property(readonly, nonatomic) double defaultTableViewSectionHeight;
@property(readonly, nonatomic) NSArray *sections;
- (Class)classForCellAtIndexPath:(id)arg1;
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (id)objectAtKeyedSubscript:(id)arg1;
- (void)registerClass:(id)arg1 forCellWithReuseIdentifier:(id)arg2 bundle:(id)arg3;
- (void)registerClass:(id)arg1 forCellWithReuseIdentifier:(id)arg2;
- (void)registerDefaultClasses;
- (id)initWithTableView:(id)arg1;
- (id)initWithTableView:(id)arg1 delegate:(id)arg2;
- (id)init;
- (void)dealloc;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

