//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString, RETableViewSection, UIImage, UIView;

@interface RETableViewItem : NSObject
{
    _Bool _enabled;
    NSString *_title;
    UIImage *_image;
    UIImage *_highlightedImage;
    long long _textAlignment;
    RETableViewSection *_section;
    NSString *_detailLabelText;
    long long _style;
    long long _selectionStyle;
    long long _accessoryType;
    long long _editingAccessoryType;
    long long _editingStyle;
    UIView *_accessoryView;
    UIView *_editingAccessoryView;
    CDUnknownBlockType _selectionHandler;
    CDUnknownBlockType _accessoryButtonTapHandler;
    CDUnknownBlockType _insertionHandler;
    CDUnknownBlockType _deletionHandler;
    CDUnknownBlockType _deletionHandlerWithCompletion;
    CDUnknownBlockType _moveHandler;
    CDUnknownBlockType _moveCompletionHandler;
    CDUnknownBlockType _cutHandler;
    CDUnknownBlockType _copyHandler;
    CDUnknownBlockType _pasteHandler;
    double _cellHeight;
    NSString *_cellIdentifier;
    CDUnknownBlockType _actionBarNavButtonTapHandler;
    CDUnknownBlockType _actionBarDoneButtonTapHandler;
    NSString *_name;
    NSArray *_validators;
    NSArray *_errors;
}

+ (id)itemWithTitle:(id)arg1 accessoryType:(long long)arg2 selectionHandler:(CDUnknownBlockType)arg3 accessoryButtonTapHandler:(CDUnknownBlockType)arg4;
+ (id)itemWithTitle:(id)arg1 accessoryType:(long long)arg2 selectionHandler:(CDUnknownBlockType)arg3;
+ (id)itemWithTitle:(id)arg1;
+ (id)item;
@property(readonly, nonatomic) NSArray *errors; // @synthesize errors=_errors;
@property(retain, nonatomic) NSArray *validators; // @synthesize validators=_validators;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) CDUnknownBlockType actionBarDoneButtonTapHandler; // @synthesize actionBarDoneButtonTapHandler=_actionBarDoneButtonTapHandler;
@property(copy, nonatomic) CDUnknownBlockType actionBarNavButtonTapHandler; // @synthesize actionBarNavButtonTapHandler=_actionBarNavButtonTapHandler;
@property(copy, nonatomic) NSString *cellIdentifier; // @synthesize cellIdentifier=_cellIdentifier;
@property(nonatomic) double cellHeight; // @synthesize cellHeight=_cellHeight;
@property(copy, nonatomic) CDUnknownBlockType pasteHandler; // @synthesize pasteHandler=_pasteHandler;
@property(copy, nonatomic) CDUnknownBlockType copyHandler; // @synthesize copyHandler=_copyHandler;
@property(copy, nonatomic) CDUnknownBlockType cutHandler; // @synthesize cutHandler=_cutHandler;
@property(copy, nonatomic) CDUnknownBlockType moveCompletionHandler; // @synthesize moveCompletionHandler=_moveCompletionHandler;
@property(copy, nonatomic) CDUnknownBlockType moveHandler; // @synthesize moveHandler=_moveHandler;
@property(copy, nonatomic) CDUnknownBlockType deletionHandlerWithCompletion; // @synthesize deletionHandlerWithCompletion=_deletionHandlerWithCompletion;
@property(copy, nonatomic) CDUnknownBlockType deletionHandler; // @synthesize deletionHandler=_deletionHandler;
@property(copy, nonatomic) CDUnknownBlockType insertionHandler; // @synthesize insertionHandler=_insertionHandler;
@property(copy, nonatomic) CDUnknownBlockType accessoryButtonTapHandler; // @synthesize accessoryButtonTapHandler=_accessoryButtonTapHandler;
@property(copy, nonatomic) CDUnknownBlockType selectionHandler; // @synthesize selectionHandler=_selectionHandler;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(retain, nonatomic) UIView *editingAccessoryView; // @synthesize editingAccessoryView=_editingAccessoryView;
@property(retain, nonatomic) UIView *accessoryView; // @synthesize accessoryView=_accessoryView;
@property(nonatomic) long long editingStyle; // @synthesize editingStyle=_editingStyle;
@property(nonatomic) long long editingAccessoryType; // @synthesize editingAccessoryType=_editingAccessoryType;
@property(nonatomic) long long accessoryType; // @synthesize accessoryType=_accessoryType;
@property(nonatomic) long long selectionStyle; // @synthesize selectionStyle=_selectionStyle;
@property(nonatomic) long long style; // @synthesize style=_style;
@property(copy, nonatomic) NSString *detailLabelText; // @synthesize detailLabelText=_detailLabelText;
@property(nonatomic) __weak RETableViewSection *section; // @synthesize section=_section;
@property(nonatomic) long long textAlignment; // @synthesize textAlignment=_textAlignment;
@property(retain, nonatomic) UIImage *highlightedImage; // @synthesize highlightedImage=_highlightedImage;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (void)deleteRowWithAnimation:(long long)arg1;
- (void)reloadRowWithAnimation:(long long)arg1;
- (void)deselectRowAnimated:(_Bool)arg1;
- (void)selectRowAnimated:(_Bool)arg1 scrollPosition:(long long)arg2;
- (void)selectRowAnimated:(_Bool)arg1;
- (id)indexPath;
- (id)init;
- (id)initWithTitle:(id)arg1 accessoryType:(long long)arg2 selectionHandler:(CDUnknownBlockType)arg3 accessoryButtonTapHandler:(CDUnknownBlockType)arg4;
- (id)initWithTitle:(id)arg1 accessoryType:(long long)arg2 selectionHandler:(CDUnknownBlockType)arg3;
- (id)initWithTitle:(id)arg1;
- (_Bool)isSelected;
@property(retain, nonatomic) id userData;

@end

