//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface REValidation : NSObject
{
    NSMutableDictionary *_registeredValidators;
    NSMutableDictionary *_errorMessages;
}

+ (id)validateObject:(id)arg1 name:(id)arg2 validators:(id)arg3;
+ (id)validateObject:(id)arg1 name:(id)arg2 validator:(id)arg3;
+ (id)validateObject:(id)arg1 name:(id)arg2 validatorString:(id)arg3;
+ (void)setErrorMessages:(id)arg1;
+ (void)setErrorMessage:(id)arg1 forDomain:(id)arg2;
+ (id)errorMessageForDomain:(id)arg1;
+ (void)registerDefaultErrorMessages;
+ (void)registerDefaultValidators;
+ (void)registerValidator:(Class)arg1;
+ (id)sharedObject;
@property(retain, nonatomic) NSMutableDictionary *errorMessages; // @synthesize errorMessages=_errorMessages;
@property(retain, nonatomic) NSMutableDictionary *registeredValidators; // @synthesize registeredValidators=_registeredValidators;
- (void).cxx_destruct;
- (id)init;

@end

