//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImage.h>

@interface UIImage (Additions)
+ (id)imageWithSize:(struct CGSize)arg1 color:(id)arg2;
- (id)initWithSize:(struct CGSize)arg1 color:(id)arg2;
@end

