//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

@class NSArray, NSString;

@interface VTAcknowledgementsViewController : UITableViewController
{
    NSArray *_acknowledgements;
    NSString *_headerText;
    NSString *_footerText;
    NSString *_acknowledgementsPlistName;
}

+ (id)localizedCocoaPodsFooterText;
+ (id)localizedTitle;
+ (id)localizedStringForKey:(id)arg1 withDefault:(id)arg2;
+ (id)acknowledgementsViewController;
+ (id)defaultAcknowledgementsPlistPath;
+ (id)acknowledgementsPlistPathForName:(id)arg1;
@property(copy, nonatomic) NSString *acknowledgementsPlistName; // @synthesize acknowledgementsPlistName=_acknowledgementsPlistName;
@property(copy, nonatomic) NSString *footerText; // @synthesize footerText=_footerText;
@property(copy, nonatomic) NSString *headerText; // @synthesize headerText=_headerText;
@property(retain, nonatomic) NSArray *acknowledgements; // @synthesize acknowledgements=_acknowledgements;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)dismissViewController:(id)arg1;
- (void)openCocoaPodsWebsite:(id)arg1;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (double)heightForLabelWithText:(id)arg1 andWidth:(double)arg2;
- (void)configureFooterView;
- (void)configureHeaderView;
- (void)viewDidLoad;
- (void)commonInitWithAcknowledgementsPlistPath:(id)arg1;
- (void)awakeFromNib;
- (id)initWithAcknowledgementsPlistPath:(id)arg1;

@end

