//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ZBarSymbolSet;

@interface ZBarImageScanner : NSObject
{
    struct zbar_image_scanner_s *scanner;
}

- (long long)scanImage:(id)arg1;
- (void)setSymbology:(int)arg1 config:(int)arg2 to:(int)arg3;
- (void)parseConfig:(id)arg1;
@property(readonly, nonatomic) ZBarSymbolSet *results; // @dynamic results;
@property(nonatomic) _Bool enableCache; // @dynamic enableCache;
- (void)dealloc;
- (id)init;

@end

