//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AVCaptureOutput, AVCaptureVideoDataOutput, ZBarCVImage, ZBarImage, ZBarImageScanner;
@protocol ZBarCaptureDelegate;

@interface ZBarCaptureReader : NSObject
{
    AVCaptureVideoDataOutput *captureOutput;
    id <ZBarCaptureDelegate> captureDelegate;
    ZBarImageScanner *scanner;
    struct CGRect scanCrop;
    struct CGSize size;
    double framesPerSecond;
    _Bool enableCache;
    struct dispatch_queue_s *queue;
    ZBarImage *image;
    ZBarCVImage *result;
    unsigned int state;
    int framecnt;
    unsigned int width;
    unsigned int height;
    unsigned long long t_frame;
    unsigned long long t_fps;
    unsigned long long t_scan;
    double dt_frame;
}

@property(nonatomic) _Bool enableCache; // @synthesize enableCache;
@property(readonly, nonatomic) double framesPerSecond; // @synthesize framesPerSecond;
@property(readonly, nonatomic) struct CGSize size; // @synthesize size;
@property(nonatomic) struct CGRect scanCrop; // @synthesize scanCrop;
@property(readonly, nonatomic) ZBarImageScanner *scanner; // @synthesize scanner;
@property(nonatomic) id <ZBarCaptureDelegate> captureDelegate; // @synthesize captureDelegate;
@property(readonly, nonatomic) AVCaptureOutput *captureOutput; // @synthesize captureOutput;
- (void)captureOutput:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;
- (void)updateSize:(struct __CFDictionary *)arg1;
- (void)setSize:(struct CGSize)arg1;
- (void)updateFPS:(id)arg1;
- (void)setFramesPerSecond:(double)arg1;
- (void)didReadNewSymbolsFromImage:(id)arg1;
- (void)didTrackSymbols:(id)arg1;
- (void)cropUpdate;
- (void)captureFrame;
- (void)flushCache;
- (void)willStopRunning;
- (void)willStartRunning;
@property(nonatomic) _Bool enableReader; // @dynamic enableReader;
- (void)dealloc;
- (id)init;
- (id)initWithImageScanner:(id)arg1;
- (void)initResult;

@end

