//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIPanGestureRecognizer.h>

@class NSNumber, UIScrollView;

@interface ZFDetectScrollViewEndGestureRecognizer : UIPanGestureRecognizer
{
    UIScrollView *_scrollview;
    NSNumber *_isFail;
}

@property(retain, nonatomic) NSNumber *isFail; // @synthesize isFail=_isFail;
@property(nonatomic) __weak UIScrollView *scrollview; // @synthesize scrollview=_scrollview;
- (void).cxx_destruct;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)reset;

@end

