//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIPercentDrivenInteractiveTransition.h>

#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UIViewControllerAnimatedTransitioning-Protocol.h"
#import "UIViewControllerTransitioningDelegate-Protocol.h"

@class NSString, UIGestureRecognizer, UIViewController, ZFDetectScrollViewEndGestureRecognizer;
@protocol UIViewControllerContextTransitioning;

@interface ZFModalTransitionAnimator : UIPercentDrivenInteractiveTransition <UIViewControllerAnimatedTransitioning, UIViewControllerTransitioningDelegate, UIGestureRecognizerDelegate>
{
    _Bool _dragable;
    _Bool _bounces;
    _Bool _isDismiss;
    _Bool _isInteractive;
    ZFDetectScrollViewEndGestureRecognizer *_gesture;
    UIGestureRecognizer *_gestureRecognizerToFailPan;
    unsigned long long _direction;
    double _behindViewScale;
    double _behindViewAlpha;
    double _transitionDuration;
    UIViewController *_modalController;
    id <UIViewControllerContextTransitioning> _transitionContext;
    double _panLocationStart;
    struct CATransform3D _tempTransform;
}

@property struct CATransform3D tempTransform; // @synthesize tempTransform=_tempTransform;
@property _Bool isInteractive; // @synthesize isInteractive=_isInteractive;
@property _Bool isDismiss; // @synthesize isDismiss=_isDismiss;
@property double panLocationStart; // @synthesize panLocationStart=_panLocationStart;
@property(retain, nonatomic) id <UIViewControllerContextTransitioning> transitionContext; // @synthesize transitionContext=_transitionContext;
@property(nonatomic) __weak UIViewController *modalController; // @synthesize modalController=_modalController;
@property double transitionDuration; // @synthesize transitionDuration=_transitionDuration;
@property double behindViewAlpha; // @synthesize behindViewAlpha=_behindViewAlpha;
@property double behindViewScale; // @synthesize behindViewScale=_behindViewScale;
@property(nonatomic) unsigned long long direction; // @synthesize direction=_direction;
@property _Bool bounces; // @synthesize bounces=_bounces;
@property(nonatomic) UIGestureRecognizer *gestureRecognizerToFailPan; // @synthesize gestureRecognizerToFailPan=_gestureRecognizerToFailPan;
@property(retain, nonatomic) ZFDetectScrollViewEndGestureRecognizer *gesture; // @synthesize gesture=_gesture;
@property(nonatomic, getter=isDragable) _Bool dragable; // @synthesize dragable=_dragable;
- (void).cxx_destruct;
- (void)orientationChanged:(id)arg1;
- (_Bool)isPriorToIOS8;
- (_Bool)gestureRecognizer:(id)arg1 shouldRequireFailureOfGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldBeRequiredToFailByGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (id)interactionControllerForDismissal:(id)arg1;
- (id)interactionControllerForPresentation:(id)arg1;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (void)cancelInteractiveTransition;
- (void)finishInteractiveTransition;
- (void)updateInteractiveTransition:(double)arg1;
- (void)startInteractiveTransition:(id)arg1;
- (void)handlePan:(id)arg1;
- (void)removeGestureRecognizerFromModalController;
- (void)animateTransition:(id)arg1;
- (double)transitionDuration:(id)arg1;
- (void)animationEnded:(_Bool)arg1;
- (void)setContentScrollView:(id)arg1;
- (void)dealloc;
- (id)initWithModalViewController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

