//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIResponder.h>

#import "UIApplicationDelegate-Protocol.h"

@class NSString, UIWindow;

@interface AppDelegate : UIResponder <UIApplicationDelegate>
{
    UIWindow *_window;
}

@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void).cxx_destruct;
- (void)languageDidChangeNotification:(id)arg1;
- (void)cleanDocumentInboxDelay:(double)arg1;
- (void)setupSubscribes;
- (void)setupNotifications;
- (void)setupMigrations;
- (void)setupBackgroundTasks;
- (void)setupAppLanguage;
- (void)syncConfigObject:(id)arg1 userInfo:(id)arg2;
- (void)configWillSyncNotification:(id)arg1;
- (void)handleOverwriteConfigFileWithURL:(id)arg1;
- (void)saveConfigFileWithURL:(id)arg1;
- (_Bool)application:(id)arg1 openURL:(id)arg2 options:(id)arg3;
- (_Bool)importConfigFileWithURL:(id)arg1;
- (_Bool)xCallbackWithURL:(id)arg1;
- (_Bool)parseXCallbackWithURL:(id)arg1 ok:(_Bool)arg2;
- (_Bool)importServersWithURL:(id)arg1;
- (void)application:(id)arg1 performActionForShortcutItem:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)suspendApplication;
- (void)applicationWillTerminate:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

