//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/NSLayoutManager.h>

@class UIColor, UIFont;

@interface CYRLayoutManager : NSLayoutManager
{
    UIFont *_lineNumberFont;
    UIColor *_lineNumberColor;
    UIColor *_selectedLineNumberColor;
    double _gutterWidth;
    unsigned long long _lastParaLocation;
    unsigned long long _lastParaNumber;
    struct _NSRange _selectedRange;
    struct UIEdgeInsets _lineAreaInset;
}

@property(nonatomic) unsigned long long lastParaNumber; // @synthesize lastParaNumber=_lastParaNumber;
@property(nonatomic) unsigned long long lastParaLocation; // @synthesize lastParaLocation=_lastParaLocation;
@property(nonatomic) struct UIEdgeInsets lineAreaInset; // @synthesize lineAreaInset=_lineAreaInset;
@property(nonatomic) struct _NSRange selectedRange; // @synthesize selectedRange=_selectedRange;
@property(nonatomic) double gutterWidth; // @synthesize gutterWidth=_gutterWidth;
@property(retain, nonatomic) UIColor *selectedLineNumberColor; // @synthesize selectedLineNumberColor=_selectedLineNumberColor;
@property(retain, nonatomic) UIColor *lineNumberColor; // @synthesize lineNumberColor=_lineNumberColor;
@property(retain, nonatomic) UIFont *lineNumberFont; // @synthesize lineNumberFont=_lineNumberFont;
- (void).cxx_destruct;
- (void)drawBackgroundForGlyphRange:(struct _NSRange)arg1 atPoint:(struct CGPoint)arg2;
- (void)processEditingForTextStorage:(id)arg1 edited:(unsigned long long)arg2 range:(struct _NSRange)arg3 changeInLength:(long long)arg4 invalidatedRange:(struct _NSRange)arg5;
- (unsigned long long)_paraNumberForRange:(struct _NSRange)arg1;
- (struct CGRect)paragraphRectForRange:(struct _NSRange)arg1;
- (void)_commonSetup;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

