//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITextView.h>

@class CYRLayoutManager, CYRTextStorage, NSArray, UIColor, UIPanGestureRecognizer;

@interface CYRTextView : UITextView
{
    struct _NSRange startRange;
    _Bool _lineCursorEnabled;
    UIPanGestureRecognizer *_singleFingerPanRecognizer;
    UIPanGestureRecognizer *_doubleFingerPanRecognizer;
    UIColor *_gutterBackgroundColor;
    UIColor *_gutterLineColor;
    CYRLayoutManager *_lineNumberLayoutManager;
    CYRTextStorage *_syntaxTextStorage;
}

@property(retain, nonatomic) CYRTextStorage *syntaxTextStorage; // @synthesize syntaxTextStorage=_syntaxTextStorage;
@property(retain, nonatomic) CYRLayoutManager *lineNumberLayoutManager; // @synthesize lineNumberLayoutManager=_lineNumberLayoutManager;
@property(nonatomic) _Bool lineCursorEnabled; // @synthesize lineCursorEnabled=_lineCursorEnabled;
@property(retain) UIColor *gutterLineColor; // @synthesize gutterLineColor=_gutterLineColor;
@property(retain) UIColor *gutterBackgroundColor; // @synthesize gutterBackgroundColor=_gutterBackgroundColor;
@property(retain, nonatomic) UIPanGestureRecognizer *doubleFingerPanRecognizer; // @synthesize doubleFingerPanRecognizer=_doubleFingerPanRecognizer;
@property(retain, nonatomic) UIPanGestureRecognizer *singleFingerPanRecognizer; // @synthesize singleFingerPanRecognizer=_singleFingerPanRecognizer;
- (void).cxx_destruct;
- (void)doubleFingerPanHappend:(id)arg1;
- (void)singleFingerPanHappend:(id)arg1;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)setText:(id)arg1;
@property(retain, nonatomic) NSArray *tokens;
- (void)handleTextViewDidChangeNotification:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;
- (void)_commonSetup;
- (id)initWithFrame:(struct CGRect)arg1;

@end

