//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RETableViewItem.h"

@class NSArray;

@interface DLWBarChartTableViewItem : RETableViewItem
{
    NSArray *_xLabels;
    NSArray *_yValues;
}

@property(retain, nonatomic) NSArray *yValues; // @synthesize yValues=_yValues;
@property(retain, nonatomic) NSArray *xLabels; // @synthesize xLabels=_xLabels;
- (void).cxx_destruct;

@end

