//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FMDatabase, NSString;

@interface DLWConfigReader : NSObject
{
    NSString *_path;
    FMDatabase *_db;
}

@property(retain, nonatomic) FMDatabase *db; // @synthesize db=_db;
@property(copy, nonatomic) NSString *path; // @synthesize path=_path;
- (void).cxx_destruct;
- (void)dealloc;
- (void)saveObjects:(id)arg1;
- (void)saveObject:(id)arg1;
- (void)removeObjectAtId:(long long)arg1;
- (void)truncate;
- (id)queryProxies;
- (id)parseProxyWithName:(id)arg1 value:(id)arg2;
- (id)querySummary;
- (id)queryWithSection:(id)arg1;
- (id)queryWithKeyword:(id)arg1 section:(id)arg2;
- (id)queryWithLessThan:(long long)arg1;
- (id)queryWithGreaterThan:(long long)arg1 section:(id)arg2;
- (id)executeQuery:(id)arg1;
- (id)initWithName:(id)arg1;
- (id)initWithPath:(id)arg1;

@end

