//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DLWViewController.h"

@class NSArray, NSDictionary, REBoolItem, RERadioItem, RETextItem, UIButton;

@interface DLWConfigRuleViewController : DLWViewController
{
    _Bool _synchronized;
    NSDictionary *_data;
    NSArray *_types;
    UIButton *_saveButton;
    RERadioItem *_typeRadioItem;
    RERadioItem *_optionRadioItem;
    RETextItem *_valueTextItem;
    REBoolItem *_boolItem;
}

@property(retain, nonatomic) REBoolItem *boolItem; // @synthesize boolItem=_boolItem;
@property(retain, nonatomic) RETextItem *valueTextItem; // @synthesize valueTextItem=_valueTextItem;
@property(retain, nonatomic) RERadioItem *optionRadioItem; // @synthesize optionRadioItem=_optionRadioItem;
@property(retain, nonatomic) RERadioItem *typeRadioItem; // @synthesize typeRadioItem=_typeRadioItem;
@property(retain, nonatomic) UIButton *saveButton; // @synthesize saveButton=_saveButton;
@property(retain, nonatomic) NSArray *types; // @synthesize types=_types;
@property(nonatomic) _Bool synchronized; // @synthesize synchronized=_synchronized;
@property(retain, nonatomic) NSDictionary *data; // @synthesize data=_data;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didLoadCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)saveButtonTouched;
- (void)setupSaveButton;
- (void)updateValueItem;
- (void)setupTableViewManager;
- (void)viewDidLoad;
- (id)initWithData:(id)arg1 synchronized:(_Bool)arg2;
- (id)initWithData:(id)arg1;

@end

