//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DLWViewController.h"

@class DLWConfigReader, NSMutableDictionary;

@interface DLWConfigMitmViewController : DLWViewController
{
    DLWConfigReader *_configReader;
    unsigned long long _backgroundUpdateTask;
    NSMutableDictionary *_map;
}

@property(retain, nonatomic) NSMutableDictionary *map; // @synthesize map=_map;
@property(nonatomic) unsigned long long backgroundUpdateTask; // @synthesize backgroundUpdateTask=_backgroundUpdateTask;
@property(retain, nonatomic) DLWConfigReader *configReader; // @synthesize configReader=_configReader;
- (void).cxx_destruct;
- (_Bool)trustEvaluateCertificate;
- (void)saveValue:(id)arg1 forName:(id)arg2;
- (void)refreshButtonTouched;
- (void)setupTableViewManager;
- (void)setupRefreshButton;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithConfigReader:(id)arg1;

@end

