//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DLWViewController.h"

@class DLWConfigReader, NSString;

@interface DLWConfigViewController : DLWViewController
{
    NSString *_file;
    DLWConfigReader *_configReader;
}

@property(retain, nonatomic) DLWConfigReader *configReader; // @synthesize configReader=_configReader;
@property(copy, nonatomic) NSString *file; // @synthesize file=_file;
- (void).cxx_destruct;
- (id)previewActionItems;
- (void)configItemWillAddNotification:(id)arg1;
- (void)configItemWillDeleteNotification:(id)arg1;
- (void)configItemWillChangeNotification:(id)arg1;
- (void)tryReloadCurrentConfig;
- (void)showAddURLRewriteController;
- (void)showAddHostController;
- (void)showAddRuleController;
- (void)viewWillAppear:(_Bool)arg1;
- (void)setupTableViewManager;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithFile:(id)arg1;

@end

