//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DLWViewController.h"

#import "UIDocumentMenuDelegate-Protocol.h"
#import "UIDocumentPickerDelegate-Protocol.h"
#import "UIViewControllerPreviewingDelegate-Protocol.h"

@class NSString;

@interface DLWDataViewController : DLWViewController <UIViewControllerPreviewingDelegate, UIDocumentMenuDelegate, UIDocumentPickerDelegate>
{
}

- (id)tabImageName;
- (id)tabTitle;
- (void)showImportViewControllerWithSourceView:(id)arg1;
- (void)showExportViewControllerWithSourceView:(id)arg1;
- (void)documentPickerWasCancelled:(id)arg1;
- (void)documentPicker:(id)arg1 didPickDocumentAtURL:(id)arg2;
- (void)documentMenu:(id)arg1 didPickDocumentPicker:(id)arg2;
- (void)setupTableViewManager;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

