//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DLWViewController.h"

#import "DLWAsyncDnsDelegate-Protocol.h"

@class DLWAsyncDns, NSMutableArray, NSString, RETableViewItem;

@interface DLWDiagnosticsViewController : DLWViewController <DLWAsyncDnsDelegate>
{
    NSMutableArray *_servers;
    DLWAsyncDns *_sock;
    RETableViewItem *_proxyItem;
}

@property(retain, nonatomic) RETableViewItem *proxyItem; // @synthesize proxyItem=_proxyItem;
@property(retain, nonatomic) DLWAsyncDns *sock; // @synthesize sock=_sock;
@property(retain, nonatomic) NSMutableArray *servers; // @synthesize servers=_servers;
- (void).cxx_destruct;
- (void)dealloc;
- (void)asyncDns:(id)arg1 queryHost:(id)arg2 didResolveRecords:(id)arg3 error:(id)arg4;
- (void)tableView:(id)arg1 willLoadCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)checkProxyServerWithBlock:(CDUnknownBlockType)arg1;
- (_Bool)checkDNSPortInUse:(int)arg1;
- (id)systemProxySettings;
- (id)systemNameServers;
- (id)networkInterfaces;
- (int)interfaceMTU:(struct ifaddrs *)arg1;
- (void)asyncResolve;
- (void)setupTableViewManager;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

