//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSDictionary;

@interface DLWEnvironItem : NSObject <NSCoding>
{
    NSDictionary *_meta;
}

@property(retain, nonatomic) NSDictionary *meta; // @synthesize meta=_meta;
- (void).cxx_destruct;
- (id)rule;
- (id)type;
- (id)group;
- (id)uuid;
- (id)routing;
- (id)value;
- (id)remark;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithMeta:(id)arg1;

@end

