//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

#import "RETableViewManagerDelegate-Protocol.h"

@class NSArray, NSString, RETableViewCellStyle, RETableViewManager;
@protocol RETableViewManagerDelegate;

@interface DLWFlagsViewController : UITableViewController <RETableViewManagerDelegate>
{
    NSArray *_options;
    NSString *_flag;
    RETableViewManager *_tableViewManager;
    CDUnknownBlockType _completionHandler;
    RETableViewCellStyle *_style;
    id <RETableViewManagerDelegate> _delegate;
}

@property(nonatomic) __weak id <RETableViewManagerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) RETableViewCellStyle *style; // @synthesize style=_style;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
@property(retain, nonatomic) RETableViewManager *tableViewManager; // @synthesize tableViewManager=_tableViewManager;
@property(copy, nonatomic) NSString *flag; // @synthesize flag=_flag;
@property(retain, nonatomic) NSArray *options; // @synthesize options=_options;
- (void).cxx_destruct;
- (void)viewDidLoad;
- (id)initWithCompletionHandler:(CDUnknownBlockType)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

