//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSFileHandle, NSString;

@interface DLWFileReader : NSObject
{
    NSString *lineDelimiter;
    unsigned long long chunkSize;
    NSFileHandle *_fileHandle;
    NSString *_filePath;
    unsigned long long _totalFileLength;
    unsigned long long _currentOffset;
}

@property(nonatomic) unsigned long long currentOffset; // @synthesize currentOffset=_currentOffset;
@property(nonatomic) unsigned long long totalFileLength; // @synthesize totalFileLength=_totalFileLength;
@property(copy, nonatomic) NSString *filePath; // @synthesize filePath=_filePath;
@property(retain, nonatomic) NSFileHandle *fileHandle; // @synthesize fileHandle=_fileHandle;
@property(nonatomic) unsigned long long chunkSize; // @synthesize chunkSize;
@property(copy, nonatomic) NSString *lineDelimiter; // @synthesize lineDelimiter;
- (void).cxx_destruct;
- (void)enumerateLinesUsingBlock:(CDUnknownBlockType)arg1;
- (void)close;
- (id)readTrimmedLine;
- (id)readLine;
- (void)dealloc;
- (id)initWithFilePath:(id)arg1;

@end

