//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSString;

@interface DLWGroupManager : NSObject
{
    _Bool _enabled;
    int _timeout;
    int _interval;
    int _tolerance;
    long long _index;
    NSString *_url;
    NSMutableArray *_groups;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableArray *groups; // @synthesize groups=_groups;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(nonatomic) int tolerance; // @synthesize tolerance=_tolerance;
@property(nonatomic) int interval; // @synthesize interval=_interval;
@property(nonatomic) int timeout; // @synthesize timeout=_timeout;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(nonatomic) long long index; // @synthesize index=_index;
- (void).cxx_destruct;
- (void)repair;
- (_Bool)synchronize;
- (void)replaceGroup:(id)arg1 with:(id)arg2;
- (void)removeGroup:(id)arg1;
- (void)addGroup:(id)arg1;
- (void)useGroup:(id)arg1;
- (id)groupWithName:(id)arg1;
- (id)selectedGroup;
- (id)allGroupNames;
- (id)allGroups;
- (id)groupServers;
- (id)groupsFile;
- (void)reload;
- (id)init;

@end

