//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RETableViewCell.h"

@class CAShapeLayer, UILabel;

@interface DLWHostTableViewCell : RETableViewCell
{
    CAShapeLayer *_dotLayer;
    UILabel *_typeLabel;
    UILabel *_pingLabel;
}

@property(nonatomic) __weak UILabel *pingLabel; // @synthesize pingLabel=_pingLabel;
@property(nonatomic) __weak UILabel *typeLabel; // @synthesize typeLabel=_typeLabel;
@property(nonatomic) __weak CAShapeLayer *dotLayer; // @synthesize dotLayer=_dotLayer;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)updatePingResult;
- (void)cellWillAppear;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

