//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface DLWIterativeMigrator : NSObject
{
}

+ (id)urlForModelName:(id)arg1 inDirectory:(id)arg2;
+ (id)modelPathsInDirectory:(id)arg1;
+ (id)modelsNamed:(id)arg1 error:(id *)arg2;
+ (id)modelForStoreMetadata:(id)arg1 error:(id *)arg2;
+ (id)metadataForPersistentStoreOfType:(id)arg1 URL:(id)arg2 error:(id *)arg3;
+ (id)errorWithCode:(long long)arg1 description:(id)arg2;
+ (id)errorDomain;
+ (_Bool)migrateURL:(id)arg1 ofType:(id)arg2 fromModel:(id)arg3 toModel:(id)arg4 mappingModel:(id)arg5 error:(id *)arg6;
+ (_Bool)iterativeMigrateURL:(id)arg1 ofType:(id)arg2 toModel:(id)arg3 orderedModelNames:(id)arg4 error:(id *)arg5;

@end

