//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DLWViewController.h"

@class NSDictionary;

@interface DLWLoggingDetailViewController : DLWViewController
{
    NSDictionary *_data;
}

@property(retain, nonatomic) NSDictionary *data; // @synthesize data=_data;
- (void).cxx_destruct;
- (id)previewActionItems;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)moreButtonTouched:(id)arg1;
- (void)setupMoreButton;
- (void)setupTableViewManager;
- (void)viewDidLoad;
- (id)initWithData:(id)arg1;

@end

