//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UISearchResultsUpdating-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class DLWLoggingReader, NSMutableArray, NSString, UITableView;

@interface DLWLoggingSearchController : UIViewController <UITableViewDelegate, UITableViewDataSource, UISearchResultsUpdating>
{
    _Bool _proxyLogging;
    _Bool _loadMoreAvailable;
    NSString *_searchScope;
    UITableView *_tableView;
    DLWLoggingReader *_loggingReader;
    NSMutableArray *_searchData;
    NSString *_searchText;
}

@property(copy, nonatomic) NSString *searchText; // @synthesize searchText=_searchText;
@property(nonatomic) _Bool loadMoreAvailable; // @synthesize loadMoreAvailable=_loadMoreAvailable;
@property(retain, nonatomic) NSMutableArray *searchData; // @synthesize searchData=_searchData;
@property(retain, nonatomic) DLWLoggingReader *loggingReader; // @synthesize loggingReader=_loggingReader;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(copy, nonatomic) NSString *searchScope; // @synthesize searchScope=_searchScope;
@property(nonatomic) _Bool proxyLogging; // @synthesize proxyLogging=_proxyLogging;
- (void).cxx_destruct;
- (void)updateSearchResultsForSearchController:(id)arg1;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 performAction:(SEL)arg2 forRowAtIndexPath:(id)arg3 withSender:(id)arg4;
- (_Bool)tableView:(id)arg1 canPerformAction:(SEL)arg2 forRowAtIndexPath:(id)arg3 withSender:(id)arg4;
- (_Bool)tableView:(id)arg1 shouldShowMenuForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)loadMoreData;
- (void)viewWillLayoutSubviews;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)setupTableView;
- (void)viewDidLoad;
- (id)initWithReader:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

