//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DLWViewController.h"

@class RETableViewItem, UIImageView;

@interface DLWProxyShareViewController : DLWViewController
{
    UIImageView *_qrImageView;
    RETableViewItem *_addressItem;
}

@property(nonatomic) __weak RETableViewItem *addressItem; // @synthesize addressItem=_addressItem;
@property(nonatomic) __weak UIImageView *qrImageView; // @synthesize qrImageView=_qrImageView;
- (void).cxx_destruct;
- (void)sendProxyShareTask;
- (id)resizeImage:(id)arg1 withQuality:(int)arg2 rate:(double)arg3;
- (id)createQRForString:(id)arg1;
- (id)IPAddress;
- (void)updateQrImageView;
- (void)setupTableViewManager;
- (id)randomStringWithLength:(int)arg1;
- (void)viewDidLoad;
- (id)init;

@end

