//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DLWViewController.h"

@class RERadioItem, RETableViewItem;

@interface DLWProxyViewController : DLWViewController
{
    RERadioItem *_typeRadioItem;
    RETableViewItem *_portTextItem;
}

@property(retain, nonatomic) RETableViewItem *portTextItem; // @synthesize portTextItem=_portTextItem;
@property(retain, nonatomic) RERadioItem *typeRadioItem; // @synthesize typeRadioItem=_typeRadioItem;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 willLayoutCellSubviews:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)reassertTunnelProvider;
- (void)setupProxyTimeoutTask:(long long)arg1;
- (void)enableLoggingTask:(_Bool)arg1;
- (void)changePortButtonTouched;
- (void)setupTableViewManager;
- (void)viewDidLoad;
- (id)init;

@end

