//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DLWViewController.h"

@class REBoolItem, RETextItem;

@interface DLWProxyChainViewController : DLWViewController
{
    RETextItem *_passwordTextItem;
    REBoolItem *_enableItem;
    REBoolItem *_systemItem;
}

@property(retain, nonatomic) REBoolItem *systemItem; // @synthesize systemItem=_systemItem;
@property(retain, nonatomic) REBoolItem *enableItem; // @synthesize enableItem=_enableItem;
@property(retain, nonatomic) RETextItem *passwordTextItem; // @synthesize passwordTextItem=_passwordTextItem;
- (void).cxx_destruct;
- (void)sendProxyChainTask;
- (void)eyeButtonTouched:(id)arg1;
- (void)refreshButtonTouched;
- (void)setupRefreshButton;
- (void)setupTableViewManager;
- (void)viewDidLoad;
- (id)init;

@end

