//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface DLWRuleMatcherResult : NSObject
{
    _Bool _proxy;
    _Bool _direct;
    _Bool _reject;
    _Bool _rewrite;
    long long _value;
    long long _policy;
    NSString *_expression;
}

@property(copy, nonatomic) NSString *expression; // @synthesize expression=_expression;
@property(nonatomic) long long policy; // @synthesize policy=_policy;
@property(nonatomic) long long value; // @synthesize value=_value;
@property(nonatomic) _Bool rewrite; // @synthesize rewrite=_rewrite;
@property(nonatomic) _Bool reject; // @synthesize reject=_reject;
@property(nonatomic) _Bool direct; // @synthesize direct=_direct;
@property(nonatomic) _Bool proxy; // @synthesize proxy=_proxy;
- (void).cxx_destruct;
- (id)string;
- (id)ruleTypeString;
- (id)policyString;
- (_Bool)isAvailable;
- (_Bool)isRejectRule;
- (_Bool)isDirectRule;
- (_Bool)isProxyRule;
- (_Bool)isRemoteResolve;
- (int)serverIndex;
- (unsigned short)order;
- (_Bool)noResolve;
- (id)init;

@end

