//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DLWOptionsViewController.h"

#import "UIViewControllerPreviewingDelegate-Protocol.h"

@class NSString;

@interface DLWRoutingViewController : DLWOptionsViewController <UIViewControllerPreviewingDelegate>
{
}

- (void)previewingContext:(id)arg1 commitViewController:(id)arg2;
- (id)previewingContext:(id)arg1 viewControllerForLocation:(struct CGPoint)arg2;
- (void)tableView:(id)arg1 didLoadCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)viewDidLoad;
- (id)initWithItem:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

