//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DLWViewController.h"

#import "DLWObfuscationViewControllerDelegate-Protocol.h"
#import "UIDocumentMenuDelegate-Protocol.h"
#import "UIDocumentPickerDelegate-Protocol.h"

@class DLWServer, NSDictionary, NSString, REBoolItem, RERadioItem, RETableViewItem, RETableViewSection, RETextItem, UIButton;

@interface DLWServerViewController : DLWViewController <DLWObfuscationViewControllerDelegate, UIDocumentMenuDelegate, UIDocumentPickerDelegate>
{
    DLWServer *_server;
    NSString *_flagCode;
    UIButton *_saveButton;
    UIButton *_flagButton;
    RERadioItem *_typeRadioItem;
    RETextItem *_hostTextItem;
    RETextItem *_remarkTextItem;
    REBoolItem *_otaItem;
    REBoolItem *_tlsItem;
    REBoolItem *_allowInsecureItem;
    RERadioItem *_fileItem;
    RETextItem *_userTextItem;
    RETextItem *_passwordTextItem;
    RETextItem *_portTextItem;
    RERadioItem *_methodRadioItem;
    RETableViewItem *_obfsButtonItem;
    RETableViewSection *_mainSection;
    RETextItem *_urlTextItem;
    NSDictionary *_attributes;
}

@property(retain, nonatomic) NSDictionary *attributes; // @synthesize attributes=_attributes;
@property(retain, nonatomic) RETextItem *urlTextItem; // @synthesize urlTextItem=_urlTextItem;
@property(retain, nonatomic) RETableViewSection *mainSection; // @synthesize mainSection=_mainSection;
@property(retain, nonatomic) RETableViewItem *obfsButtonItem; // @synthesize obfsButtonItem=_obfsButtonItem;
@property(retain, nonatomic) RERadioItem *methodRadioItem; // @synthesize methodRadioItem=_methodRadioItem;
@property(retain, nonatomic) RETextItem *portTextItem; // @synthesize portTextItem=_portTextItem;
@property(retain, nonatomic) RETextItem *passwordTextItem; // @synthesize passwordTextItem=_passwordTextItem;
@property(retain, nonatomic) RETextItem *userTextItem; // @synthesize userTextItem=_userTextItem;
@property(retain, nonatomic) RERadioItem *fileItem; // @synthesize fileItem=_fileItem;
@property(retain, nonatomic) REBoolItem *allowInsecureItem; // @synthesize allowInsecureItem=_allowInsecureItem;
@property(retain, nonatomic) REBoolItem *tlsItem; // @synthesize tlsItem=_tlsItem;
@property(retain, nonatomic) REBoolItem *otaItem; // @synthesize otaItem=_otaItem;
@property(retain, nonatomic) RETextItem *remarkTextItem; // @synthesize remarkTextItem=_remarkTextItem;
@property(retain, nonatomic) RETextItem *hostTextItem; // @synthesize hostTextItem=_hostTextItem;
@property(retain, nonatomic) RERadioItem *typeRadioItem; // @synthesize typeRadioItem=_typeRadioItem;
@property(retain, nonatomic) UIButton *flagButton; // @synthesize flagButton=_flagButton;
@property(retain, nonatomic) UIButton *saveButton; // @synthesize saveButton=_saveButton;
@property(copy, nonatomic) NSString *flagCode; // @synthesize flagCode=_flagCode;
@property(retain, nonatomic) DLWServer *server; // @synthesize server=_server;
- (void).cxx_destruct;
- (void)documentMenu:(id)arg1 didPickDocumentPicker:(id)arg2;
- (void)documentPicker:(id)arg1 didPickDocumentAtURL:(id)arg2;
- (id)serverWithDictionary:(id)arg1;
- (void)viewWillLayoutSubviews;
- (void)obfuscationViewControllerDidUpdatedAttributes:(id)arg1;
- (id)previewActionItems;
- (void)UITextFieldTextDidChangeNotification;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)showDocumentPickerControllerWithSourceView:(id)arg1;
- (void)dlw_qrCodeScaned:(id)arg1;
- (void)qrButtonTouched:(id)arg1;
- (void)saveButtonTouched;
- (void)eyeButtonTouched:(id)arg1;
- (void)flagButtonTouched:(id)arg1;
- (void)updateSectionItems;
- (void)setupSaveButton;
- (id)sectionItemsForType:(id)arg1;
- (void)setupAddingSection;
- (void)setupEditingSection;
- (void)setupTableViewManager;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;
- (id)initWithServer:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

