//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DLWOptionsViewController.h"

#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSArray, NSDictionary, NSString, RETextItem, UITapGestureRecognizer;

@interface DLWServerPickerViewController : DLWOptionsViewController <UIGestureRecognizerDelegate>
{
    NSDictionary *_group;
    NSArray *_servers;
    RETextItem *_nameItem;
    CDUnknownBlockType _originalCompletionHandler;
    UITapGestureRecognizer *_tapGestureRecognizer;
}

@property(retain, nonatomic) UITapGestureRecognizer *tapGestureRecognizer; // @synthesize tapGestureRecognizer=_tapGestureRecognizer;
@property(copy, nonatomic) CDUnknownBlockType originalCompletionHandler; // @synthesize originalCompletionHandler=_originalCompletionHandler;
@property(retain, nonatomic) RETextItem *nameItem; // @synthesize nameItem=_nameItem;
@property(retain, nonatomic) NSArray *servers; // @synthesize servers=_servers;
@property(retain, nonatomic) NSDictionary *group; // @synthesize group=_group;
- (void).cxx_destruct;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)saveButtonTouched;
- (id)allSelectedIstems;
- (void)dlw_closeButtonTouched;
- (void)setupSaveButton;
- (void)handleTapGestureRecognizer;
- (void)viewDidLoad;
- (id)initWithItem:(id)arg1 multipleChoice:(_Bool)arg2 completionHandler:(CDUnknownBlockType)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

