//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DLWViewController.h"

#import "DLWSceneViewControllerDelegate-Protocol.h"

@class DLWSceneItem, DLWSceneManager, NSString, RETableViewSection;

@interface DLWScenesViewController : DLWViewController <DLWSceneViewControllerDelegate>
{
    RETableViewSection *_sceneSection;
    DLWSceneManager *_sceneManager;
    DLWSceneItem *_selectedScene;
}

@property(retain, nonatomic) DLWSceneItem *selectedScene; // @synthesize selectedScene=_selectedScene;
@property(retain, nonatomic) DLWSceneManager *sceneManager; // @synthesize sceneManager=_sceneManager;
@property(retain, nonatomic) RETableViewSection *sceneSection; // @synthesize sceneSection=_sceneSection;
- (void).cxx_destruct;
- (void)showSceneController:(id)arg1;
- (void)sceneViewController:(id)arg1 didModifiedScene:(id)arg2;
- (void)reloadSceneItems;
- (void)reloadTableViewData;
- (void)dealloc;
- (void)setupTableViewManager;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

