//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RETableViewCell.h"

@class CAShapeLayer;

@interface DLWSelectedTableViewCell : RETableViewCell
{
    CAShapeLayer *_dotLayer;
}

@property(retain, nonatomic) CAShapeLayer *dotLayer; // @synthesize dotLayer=_dotLayer;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)cellWillAppear;

@end

