//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RETableViewItem.h"

@interface DLWStatisticsTableViewItem : RETableViewItem
{
}

- (id)stringForWWANBytes;
- (id)stringForWiFiBytes;
- (id)stringForOutBytes;
- (id)stringForInBytes;
- (id)stringForDirectOutBytes;
- (id)stringForDirectInBytes;
- (id)stringForProxyOutBytes;
- (id)stringForProxyInBytes;
- (id)stringForInSpeed;
- (id)bytesToAvaiUnit:(long long)arg1;

@end

