//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RETableViewCell.h"

@class UILabel;

@interface DLWSceneTableViewCell : RETableViewCell
{
    UILabel *_hostLabel;
}

@property(retain, nonatomic) UILabel *hostLabel; // @synthesize hostLabel=_hostLabel;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)cellWillAppear;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

