//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DLWViewController.h"

#import "NSURLSessionDataDelegate-Protocol.h"

@class DLWBarChartTableViewItem, NSDateFormatter, NSMutableData, NSObject, NSString, NSURLSession, NSURLSessionDataTask, RETableViewItem;
@protocol OS_dispatch_source;

@interface DLWStatisticsViewController : DLWViewController <NSURLSessionDataDelegate>
{
    NSObject<OS_dispatch_source> *_timer;
    NSURLSessionDataTask *_dataTask;
    NSURLSession *_session;
    NSMutableData *_buffer;
    long long _inBytes;
    long long _outBytes;
    RETableViewItem *_startTimeItem;
    RETableViewItem *_endTimeItem;
    RETableViewItem *_serverItem;
    RETableViewItem *_timeItem;
    RETableViewItem *_statisticsItem;
    DLWBarChartTableViewItem *_barChartItem;
    NSDateFormatter *_dateFormatter;
}

@property(retain, nonatomic) NSDateFormatter *dateFormatter; // @synthesize dateFormatter=_dateFormatter;
@property(retain, nonatomic) DLWBarChartTableViewItem *barChartItem; // @synthesize barChartItem=_barChartItem;
@property(retain, nonatomic) RETableViewItem *statisticsItem; // @synthesize statisticsItem=_statisticsItem;
@property(retain, nonatomic) RETableViewItem *timeItem; // @synthesize timeItem=_timeItem;
@property(retain, nonatomic) RETableViewItem *serverItem; // @synthesize serverItem=_serverItem;
@property(retain, nonatomic) RETableViewItem *endTimeItem; // @synthesize endTimeItem=_endTimeItem;
@property(retain, nonatomic) RETableViewItem *startTimeItem; // @synthesize startTimeItem=_startTimeItem;
@property(nonatomic) long long outBytes; // @synthesize outBytes=_outBytes;
@property(nonatomic) long long inBytes; // @synthesize inBytes=_inBytes;
@property(retain, nonatomic) NSMutableData *buffer; // @synthesize buffer=_buffer;
@property(retain, nonatomic) NSURLSession *session; // @synthesize session=_session;
@property(retain, nonatomic) NSURLSessionDataTask *dataTask; // @synthesize dataTask=_dataTask;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *timer; // @synthesize timer=_timer;
- (void).cxx_destruct;
- (void)NEVPNStatusDidChangeNotification:(id)arg1;
- (void)UIApplicationDidBecomeActiveNotification;
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveData:(id)arg3;
- (id)prettyDateString:(int)arg1;
- (void)stopCheckRocketStats;
- (void)checkRocketStats;
- (void)resetStatistics;
- (void)moreButtonTouched:(id)arg1;
- (void)setupMoreButton;
- (id)barChart;
- (void)setupTableViewManager;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

