//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface DLWSceneManager : NSObject
{
    id _group;
    NSMutableArray *_scenes;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableArray *scenes; // @synthesize scenes=_scenes;
@property(retain, nonatomic) id group; // @synthesize group=_group;
- (void).cxx_destruct;
- (_Bool)synchronize;
- (void)clear;
- (void)reload;
- (id)selectedGroupServers;
- (id)all;
- (void)replaceRule:(id)arg1 withReplace:(id)arg2;
- (void)removeItem:(id)arg1;
- (void)addItem:(id)arg1;
- (id)sceneFile;
- (id)lookupSSID;
- (id)scene;
- (id)init;

@end

