//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "GCDAsyncSocketDelegate-Protocol.h"

@class GCDAsyncSocket, NSData, NSString;
@protocol DLWTcpSocketDelegate, OS_dispatch_queue;

@interface DLWTcpSocket : NSObject <GCDAsyncSocketDelegate>
{
    _Bool _success;
    id <DLWTcpSocketDelegate> _delegate;
    double _startedTime;
    double _finishedTime;
    long long _sequenceNumber;
    id _userData;
    NSData *_address;
    NSObject<OS_dispatch_queue> *_queue;
    GCDAsyncSocket *_asyncSocket;
}

@property(retain, nonatomic) GCDAsyncSocket *asyncSocket; // @synthesize asyncSocket=_asyncSocket;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(nonatomic) _Bool success; // @synthesize success=_success;
@property(retain, nonatomic) NSData *address; // @synthesize address=_address;
@property(retain, nonatomic) id userData; // @synthesize userData=_userData;
@property(nonatomic) long long sequenceNumber; // @synthesize sequenceNumber=_sequenceNumber;
@property(nonatomic) double finishedTime; // @synthesize finishedTime=_finishedTime;
@property(nonatomic) double startedTime; // @synthesize startedTime=_startedTime;
@property(nonatomic) __weak id <DLWTcpSocketDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (double)seconds;
- (void)disconnect;
- (void)connect;
- (void)socketDidDisconnect:(id)arg1 withError:(id)arg2;
- (void)socket:(id)arg1 didConnectToHost:(id)arg2 port:(unsigned short)arg3;
- (void)connectToHost:(id)arg1 port:(unsigned short)arg2;
- (id)initWithDelegate:(id)arg1 dispatchQueue:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

