//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DLWHeaderFooterView.h"

@interface DLWToggleHeaderFooterView : DLWHeaderFooterView
{
    _Bool _collapsed;
}

@property(nonatomic) _Bool collapsed; // @synthesize collapsed=_collapsed;
- (void)addTarget:(id)arg1 action:(SEL)arg2;
- (void)toggleAction;
- (id)initWithReuseIdentifier:(id)arg1;

@end

