//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DLWViewController.h"

@class NSArray, NSDictionary, RERadioItem, RETextItem, UIButton;

@interface DLWURLRewriteViewController : DLWViewController
{
    NSDictionary *_data;
    NSArray *_types;
    UIButton *_saveButton;
    RETextItem *_urlTextItem;
    RETextItem *_replaceTextItem;
    RERadioItem *_typeRadioItem;
}

@property(retain, nonatomic) RERadioItem *typeRadioItem; // @synthesize typeRadioItem=_typeRadioItem;
@property(retain, nonatomic) RETextItem *replaceTextItem; // @synthesize replaceTextItem=_replaceTextItem;
@property(retain, nonatomic) RETextItem *urlTextItem; // @synthesize urlTextItem=_urlTextItem;
@property(retain, nonatomic) UIButton *saveButton; // @synthesize saveButton=_saveButton;
@property(retain, nonatomic) NSArray *types; // @synthesize types=_types;
@property(retain, nonatomic) NSDictionary *data; // @synthesize data=_data;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didLoadCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)saveButtonTouched;
- (void)setupSaveButton;
- (void)setupTableViewManager;
- (void)viewDidLoad;
- (id)initWithItem:(id)arg1;

@end

