//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "RETableViewManagerDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSString, RETableViewManager, UITableView, UITapGestureRecognizer;

@interface DLWViewController : UIViewController <UIGestureRecognizerDelegate, RETableViewManagerDelegate>
{
    _Bool _usingKeyboardNotification;
    _Bool _keyboardIsShowing;
    _Bool _registeredKeyboardNotification;
    UITableView *_tableView;
    RETableViewManager *_tableViewManager;
    UITapGestureRecognizer *_tapGestureRecognizer;
}

@property(retain, nonatomic) UITapGestureRecognizer *tapGestureRecognizer; // @synthesize tapGestureRecognizer=_tapGestureRecognizer;
@property(nonatomic) _Bool registeredKeyboardNotification; // @synthesize registeredKeyboardNotification=_registeredKeyboardNotification;
@property(nonatomic) _Bool keyboardIsShowing; // @synthesize keyboardIsShowing=_keyboardIsShowing;
@property(retain, nonatomic) RETableViewManager *tableViewManager; // @synthesize tableViewManager=_tableViewManager;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) _Bool usingKeyboardNotification; // @synthesize usingKeyboardNotification=_usingKeyboardNotification;
- (void).cxx_destruct;
- (_Bool)accessibilityPerformEscape;
- (_Bool)shouldAutorotate;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willLayoutCellSubviews:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didLoadCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 willLoadCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)keyboardWillHideNotification:(id)arg1;
- (void)keyboardWillShowNotification:(id)arg1;
- (void)handleTapGestureRecognizer;
- (void)unregisterKeyboardNotification;
- (void)registerKeyboardNotification;
- (void)setupTableViewManager;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

