//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GCDWebServer.h"

@class NSArray, NSString;
@protocol DLWWebUploaderDelegate;

@interface DLWWebUploader : GCDWebServer
{
    NSString *_uploadDirectory;
    NSArray *_allowedExtensions;
    _Bool _allowHidden;
    NSString *_title;
    NSString *_header;
    NSString *_prologue;
    NSString *_epilogue;
    NSString *_footer;
    _Bool _allowHiddenItems;
    NSArray *_allowedFileExtensions;
}

@property(copy, nonatomic) NSString *footer; // @synthesize footer=_footer;
@property(copy, nonatomic) NSString *epilogue; // @synthesize epilogue=_epilogue;
@property(copy, nonatomic) NSString *prologue; // @synthesize prologue=_prologue;
@property(copy, nonatomic) NSString *header; // @synthesize header=_header;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) _Bool allowHiddenItems; // @synthesize allowHiddenItems=_allowHiddenItems;
@property(copy, nonatomic) NSArray *allowedFileExtensions; // @synthesize allowedFileExtensions=_allowedFileExtensions;
@property(readonly, nonatomic) NSString *uploadDirectory; // @synthesize uploadDirectory=_uploadDirectory;
- (void).cxx_destruct;
- (id)initWithUploadDirectory:(id)arg1;
- (id)deleteItem:(id)arg1;
- (id)uploadFile:(id)arg1;
- (id)downloadFile:(id)arg1;
- (id)listDirectory:(id)arg1;
- (id)_uniquePathForPath:(id)arg1;
- (_Bool)_checkFileExtension:(id)arg1;
- (_Bool)_checkSandboxedPath:(id)arg1;
- (_Bool)shouldDeleteItemAtPath:(id)arg1;
- (_Bool)shouldUploadFileAtPath:(id)arg1 withTemporaryFile:(id)arg2;

// Remaining properties
@property(nonatomic) id <DLWWebUploaderDelegate> delegate; // @dynamic delegate;

@end

