//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSLayoutConstraint.h>

@interface MASLayoutConstraint : NSLayoutConstraint
{
    id _mas_key;
}

@property(retain, nonatomic) id mas_key; // @synthesize mas_key=_mas_key;
- (void).cxx_destruct;

@end

