//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UIView;

@interface MASViewAttribute : NSObject
{
    UIView *_view;
    long long _layoutAttribute;
}

@property(readonly, nonatomic) long long layoutAttribute; // @synthesize layoutAttribute=_layoutAttribute;
@property(readonly, nonatomic) __weak UIView *view; // @synthesize view=_view;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isSizeAttribute;
- (id)initWithView:(id)arg1 layoutAttribute:(long long)arg2;

@end

