//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MF_Base64Codec : NSObject
{
}

+ (id)base64StringFromData:(id)arg1;
+ (id)dataFromBase64String:(id)arg1;
+ (id)base64UrlEncodedStringFromBase64String:(id)arg1;
+ (id)base64StringFromBase64UrlEncodedString:(id)arg1;

@end

