//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MGSwipeAnimation, UIColor;

@interface MGSwipeExpansionSettings : NSObject
{
    _Bool _fillOnTrigger;
    long long _buttonIndex;
    double _threshold;
    UIColor *_expansionColor;
    long long _expansionLayout;
    MGSwipeAnimation *_triggerAnimation;
    double _animationDuration;
}

@property(nonatomic) double animationDuration; // @synthesize animationDuration=_animationDuration;
@property(retain, nonatomic) MGSwipeAnimation *triggerAnimation; // @synthesize triggerAnimation=_triggerAnimation;
@property(nonatomic) long long expansionLayout; // @synthesize expansionLayout=_expansionLayout;
@property(retain, nonatomic) UIColor *expansionColor; // @synthesize expansionColor=_expansionColor;
@property(nonatomic) double threshold; // @synthesize threshold=_threshold;
@property(nonatomic) _Bool fillOnTrigger; // @synthesize fillOnTrigger=_fillOnTrigger;
@property(nonatomic) long long buttonIndex; // @synthesize buttonIndex=_buttonIndex;
- (void).cxx_destruct;
- (id)init;

@end

