//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MGSwipeAnimation;

@interface MGSwipeAnimationData : NSObject
{
    double _from;
    double _to;
    double _duration;
    double _start;
    MGSwipeAnimation *_animation;
}

@property(retain, nonatomic) MGSwipeAnimation *animation; // @synthesize animation=_animation;
@property(nonatomic) double start; // @synthesize start=_start;
@property(nonatomic) double duration; // @synthesize duration=_duration;
@property(nonatomic) double to; // @synthesize to=_to;
@property(nonatomic) double from; // @synthesize from=_from;
- (void).cxx_destruct;

@end

