//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@interface MGSwipeButton : UIButton
{
    CDUnknownBlockType _callback;
    double _buttonWidth;
}

+ (id)buttonWithTitle:(id)arg1 icon:(id)arg2 backgroundColor:(id)arg3 insets:(struct UIEdgeInsets)arg4 callback:(CDUnknownBlockType)arg5;
+ (id)buttonWithTitle:(id)arg1 icon:(id)arg2 backgroundColor:(id)arg3 padding:(long long)arg4 callback:(CDUnknownBlockType)arg5;
+ (id)buttonWithTitle:(id)arg1 icon:(id)arg2 backgroundColor:(id)arg3 callback:(CDUnknownBlockType)arg4;
+ (id)buttonWithTitle:(id)arg1 icon:(id)arg2 backgroundColor:(id)arg3 insets:(struct UIEdgeInsets)arg4;
+ (id)buttonWithTitle:(id)arg1 icon:(id)arg2 backgroundColor:(id)arg3 padding:(long long)arg4;
+ (id)buttonWithTitle:(id)arg1 icon:(id)arg2 backgroundColor:(id)arg3;
+ (id)buttonWithTitle:(id)arg1 backgroundColor:(id)arg2 insets:(struct UIEdgeInsets)arg3 callback:(CDUnknownBlockType)arg4;
+ (id)buttonWithTitle:(id)arg1 backgroundColor:(id)arg2 padding:(long long)arg3 callback:(CDUnknownBlockType)arg4;
+ (id)buttonWithTitle:(id)arg1 backgroundColor:(id)arg2 callback:(CDUnknownBlockType)arg3;
+ (id)buttonWithTitle:(id)arg1 backgroundColor:(id)arg2 insets:(struct UIEdgeInsets)arg3;
+ (id)buttonWithTitle:(id)arg1 backgroundColor:(id)arg2 padding:(long long)arg3;
+ (id)buttonWithTitle:(id)arg1 backgroundColor:(id)arg2;
@property(nonatomic) double buttonWidth; // @synthesize buttonWidth=_buttonWidth;
@property(copy, nonatomic) CDUnknownBlockType callback; // @synthesize callback=_callback;
- (void).cxx_destruct;
- (void)setEdgeInsets:(struct UIEdgeInsets)arg1;
- (void)setPadding:(double)arg1;
- (void)centerIconOverTextWithSpacing:(double)arg1;
- (void)centerIconOverText;
- (_Bool)callMGSwipeConvenienceCallback:(id)arg1;

@end

