//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSArray.h>

@interface NSArray (ObjectiveSugar)
- (id)symmetricDifference:(id)arg1;
- (id)relativeComplement:(id)arg1;
- (id)unionWithArray:(id)arg1;
- (id)intersectionWithArray:(id)arg1;
- (id)reverse;
- (id)sortBy:(id)arg1;
- (id)sort;
- (id)join:(id)arg1;
- (id)join;
- (id)flatten;
- (id)reject:(CDUnknownBlockType)arg1;
- (id)find:(CDUnknownBlockType)arg1;
- (id)detect:(CDUnknownBlockType)arg1;
- (id)select:(CDUnknownBlockType)arg1;
- (id)map:(CDUnknownBlockType)arg1;
- (id)takeWhile:(CDUnknownBlockType)arg1;
- (id)take:(unsigned long long)arg1;
- (_Bool)includes:(id)arg1;
- (void)eachWithIndex:(CDUnknownBlockType)arg1;
- (void)each:(CDUnknownBlockType)arg1;
- (id)objectForKeyedSubscript:(id)arg1;
- (id)sample;
- (id)last;
- (id)first;
@end

