//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSData.h>

@interface NSData (Base64Addition)
+ (id)dataWithBase64UrlEncodedString:(id)arg1;
+ (id)dataWithBase64String:(id)arg1;
- (id)base64UrlEncodedString;
- (id)base64String;
@end

