//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

@interface NSManagedObject (Mappings)
+ (id)primaryKey;
+ (id)mappings;
+ (void)cacheKey:(id)arg1 forRemoteKey:(id)arg2;
+ (id)sharedMappings;
+ (id)cachedMappings;
+ (id)objectOrSetOfObjectsFromValue:(id)arg1 ofClass:(id)arg2 inContext:(id)arg3;
+ (id)transformValue:(id)arg1 forRemoteKey:(id)arg2 inContext:(id)arg3;
+ (id)keyForRemoteKey:(id)arg1 inContext:(id)arg2;
@end

