//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

@interface NSManagedObject (ActiveRecord)
+ (unsigned long long)countForFetchWithPredicate:(id)arg1 inContext:(id)arg2;
+ (id)fetchWithCondition:(id)arg1 inContext:(id)arg2 withOrder:(id)arg3 fetchLimit:(id)arg4;
+ (id)createFetchRequestInContext:(id)arg1;
+ (id)sortDescriptorsFromObject:(id)arg1;
+ (id)sortDescriptorFromObject:(id)arg1;
+ (id)sortDescriptorFromString:(id)arg1;
+ (id)sortDescriptorFromDictionary:(id)arg1;
+ (id)predicateFromObject:(id)arg1 arguments:(char *)arg2;
+ (id)predicateFromObject:(id)arg1;
+ (id)predicateFromDictionary:(id)arg1;
+ (id)transformProperties:(id)arg1 withContext:(id)arg2;
+ (id)entityName;
+ (void)deleteAllInContext:(id)arg1;
+ (void)deleteAll;
+ (id)createInContext:(id)arg1;
+ (id)create:(id)arg1 inContext:(id)arg2;
+ (id)create:(id)arg1;
+ (id)create;
+ (unsigned long long)countWhere:(id)arg1 inContext:(id)arg2;
+ (unsigned long long)countInContext:(id)arg1;
+ (unsigned long long)countWhere:(id)arg1;
+ (unsigned long long)count;
+ (id)where:(id)arg1 inContext:(id)arg2 order:(id)arg3 limit:(id)arg4;
+ (id)where:(id)arg1 inContext:(id)arg2 limit:(id)arg3;
+ (id)where:(id)arg1 inContext:(id)arg2 order:(id)arg3;
+ (id)where:(id)arg1 inContext:(id)arg2;
+ (id)where:(id)arg1 order:(id)arg2 limit:(id)arg3;
+ (id)where:(id)arg1 limit:(id)arg2;
+ (id)where:(id)arg1 order:(id)arg2;
+ (id)where:(id)arg1;
+ (id)find:(id)arg1 inContext:(id)arg2;
+ (id)find:(id)arg1;
+ (id)findOrCreate:(id)arg1 inContext:(id)arg2;
+ (id)findOrCreate:(id)arg1;
+ (id)allInContext:(id)arg1 order:(id)arg2;
+ (id)allInContext:(id)arg1;
+ (id)allWithOrder:(id)arg1;
+ (id)all;
- (id)defaultFormatter;
- (_Bool)isIntegerAttributeType:(unsigned long long)arg1;
- (void)setSafeValue:(id)arg1 forKey:(id)arg2;
- (_Bool)saveTheContext;
- (void)delete;
- (_Bool)save;
- (void)update:(id)arg1;
@end

