//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface NSObject (JGInstanceSwizzler)
- (_Bool)deswizzle;
- (_Bool)deswizzleMethod:(SEL)arg1;
- (void)swizzleMethod:(SEL)arg1 withReplacement:(CDUnknownBlockType)arg2;
@end

