//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSSet.h>

@interface NSSet (ObjectiveSugar)
- (id)sort;
- (id)reject:(CDUnknownBlockType)arg1;
- (id)select:(CDUnknownBlockType)arg1;
- (id)map:(CDUnknownBlockType)arg1;
- (void)eachWithIndex:(CDUnknownBlockType)arg1;
- (void)each:(CDUnknownBlockType)arg1;
- (id)sample;
- (id)last;
- (id)first;
@end

