//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIColor, UIFont;

@interface PNGenericChart : UIView
{
    _Bool _hasLegend;
    _Bool _displayAnimated;
    unsigned long long _legendPosition;
    unsigned long long _legendStyle;
    UIFont *_legendFont;
    UIColor *_legendFontColor;
    unsigned long long _labelRowsInSerialMode;
}

@property(nonatomic) _Bool displayAnimated; // @synthesize displayAnimated=_displayAnimated;
@property(nonatomic) unsigned long long labelRowsInSerialMode; // @synthesize labelRowsInSerialMode=_labelRowsInSerialMode;
@property(nonatomic) UIColor *legendFontColor; // @synthesize legendFontColor=_legendFontColor;
@property(nonatomic) UIFont *legendFont; // @synthesize legendFont=_legendFont;
@property(nonatomic) unsigned long long legendStyle; // @synthesize legendStyle=_legendStyle;
@property(nonatomic) unsigned long long legendPosition; // @synthesize legendPosition=_legendPosition;
@property(nonatomic) _Bool hasLegend; // @synthesize hasLegend=_hasLegend;
- (id)getLegendWithMaxWidth:(double)arg1;
- (void)setupDefaultValues;

@end

