//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PNGenericChart.h"

@class CAShapeLayer, NSArray, NSMutableArray, UIColor, UILabel;

@interface PNRadarChart : PNGenericChart
{
    _Bool _isLabelTouchable;
    _Bool _isShowGraduation;
    NSArray *_chartData;
    double _valueDivider;
    double _maxValue;
    UIColor *_webColor;
    UIColor *_plotColor;
    UIColor *_fontColor;
    UIColor *_graduationColor;
    double _fontSize;
    unsigned long long _labelStyle;
    double _centerX;
    double _centerY;
    NSMutableArray *_pointsToWebArrayArray;
    NSMutableArray *_pointsToPlotArray;
    UILabel *_detailLabel;
    double _lengthUnit;
    CAShapeLayer *_chartPlot;
}

@property(retain, nonatomic) CAShapeLayer *chartPlot; // @synthesize chartPlot=_chartPlot;
@property(nonatomic) double lengthUnit; // @synthesize lengthUnit=_lengthUnit;
@property(retain, nonatomic) UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(retain, nonatomic) NSMutableArray *pointsToPlotArray; // @synthesize pointsToPlotArray=_pointsToPlotArray;
@property(retain, nonatomic) NSMutableArray *pointsToWebArrayArray; // @synthesize pointsToWebArrayArray=_pointsToWebArrayArray;
@property(nonatomic) double centerY; // @synthesize centerY=_centerY;
@property(nonatomic) double centerX; // @synthesize centerX=_centerX;
@property(nonatomic) _Bool isShowGraduation; // @synthesize isShowGraduation=_isShowGraduation;
@property(nonatomic) _Bool isLabelTouchable; // @synthesize isLabelTouchable=_isLabelTouchable;
@property(nonatomic) unsigned long long labelStyle; // @synthesize labelStyle=_labelStyle;
@property(nonatomic) double fontSize; // @synthesize fontSize=_fontSize;
@property(retain, nonatomic) UIColor *graduationColor; // @synthesize graduationColor=_graduationColor;
@property(retain, nonatomic) UIColor *fontColor; // @synthesize fontColor=_fontColor;
@property(retain, nonatomic) UIColor *plotColor; // @synthesize plotColor=_plotColor;
@property(retain, nonatomic) UIColor *webColor; // @synthesize webColor=_webColor;
@property(nonatomic) double maxValue; // @synthesize maxValue=_maxValue;
@property(nonatomic) double valueDivider; // @synthesize valueDivider=_valueDivider;
@property(retain, nonatomic) NSArray *chartData; // @synthesize chartData=_chartData;
- (void).cxx_destruct;
- (void)addAnimationIfNeeded;
- (double)getMaxValueFromArray:(id)arg1;
- (double)getMaxWidthLabelFromArray:(id)arg1 withFontSize:(double)arg2;
- (id)getLengthArrayWithCircleNum:(int)arg1;
- (id)getWebPointWithLength:(double)arg1 angleArray:(id)arg2;
- (void)showGraduation;
- (void)tapLabel:(id)arg1;
- (void)drawLabelWithMaxLength:(double)arg1 labelArray:(id)arg2 angleArray:(id)arg3;
- (void)strokeChart;
- (void)drawRect:(struct CGRect)arg1;
- (void)calculateChartPoints;
- (id)initWithFrame:(struct CGRect)arg1 items:(id)arg2 valueDivider:(double)arg3;

@end

