//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@class NSDictionary, NSString, UIColor, UIFont, UIImage;

@interface RDVTabBarItem : UIControl
{
    NSString *_title;
    struct UIOffset _imagePositionAdjustment;
    NSDictionary *_unselectedTitleAttributes;
    NSDictionary *_selectedTitleAttributes;
    double _itemHeight;
    NSString *_badgeValue;
    UIImage *_badgeBackgroundImage;
    UIColor *_badgeBackgroundColor;
    UIColor *_badgeTextColor;
    UIFont *_badgeTextFont;
    UIImage *_unselectedBackgroundImage;
    UIImage *_selectedBackgroundImage;
    UIImage *_unselectedImage;
    UIImage *_selectedImage;
    struct UIOffset _titlePositionAdjustment;
    struct UIOffset _badgePositionAdjustment;
}

@property(retain) UIImage *selectedImage; // @synthesize selectedImage=_selectedImage;
@property(retain) UIImage *unselectedImage; // @synthesize unselectedImage=_unselectedImage;
@property(retain) UIImage *selectedBackgroundImage; // @synthesize selectedBackgroundImage=_selectedBackgroundImage;
@property(retain) UIImage *unselectedBackgroundImage; // @synthesize unselectedBackgroundImage=_unselectedBackgroundImage;
@property(retain, nonatomic) UIFont *badgeTextFont; // @synthesize badgeTextFont=_badgeTextFont;
@property(nonatomic) struct UIOffset badgePositionAdjustment; // @synthesize badgePositionAdjustment=_badgePositionAdjustment;
@property(retain) UIColor *badgeTextColor; // @synthesize badgeTextColor=_badgeTextColor;
@property(retain) UIColor *badgeBackgroundColor; // @synthesize badgeBackgroundColor=_badgeBackgroundColor;
@property(retain) UIImage *badgeBackgroundImage; // @synthesize badgeBackgroundImage=_badgeBackgroundImage;
@property(copy, nonatomic) NSString *badgeValue; // @synthesize badgeValue=_badgeValue;
@property(nonatomic) struct UIOffset imagePositionAdjustment; // @synthesize imagePositionAdjustment=_imagePositionAdjustment;
@property(copy) NSDictionary *selectedTitleAttributes; // @synthesize selectedTitleAttributes=_selectedTitleAttributes;
@property(copy) NSDictionary *unselectedTitleAttributes; // @synthesize unselectedTitleAttributes=_unselectedTitleAttributes;
@property(nonatomic) struct UIOffset titlePositionAdjustment; // @synthesize titlePositionAdjustment=_titlePositionAdjustment;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property double itemHeight; // @synthesize itemHeight=_itemHeight;
- (void).cxx_destruct;
- (_Bool)isAccessibilityElement;
- (id)accessibilityLabel;
- (void)setBackgroundSelectedImage:(id)arg1 withUnselectedImage:(id)arg2;
- (id)backgroundUnselectedImage;
- (id)backgroundSelectedImage;
- (void)setFinishedSelectedImage:(id)arg1 withFinishedUnselectedImage:(id)arg2;
- (id)finishedUnselectedImage;
- (id)finishedSelectedImage;
- (void)drawRect:(struct CGRect)arg1;
- (void)commonInitialization;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

