//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RETableViewItem.h"

@interface REBoolItem : RETableViewItem
{
    _Bool _value;
    CDUnknownBlockType _switchValueChangeHandler;
}

+ (id)itemWithTitle:(id)arg1 value:(_Bool)arg2 switchValueChangeHandler:(CDUnknownBlockType)arg3;
+ (id)itemWithTitle:(id)arg1 value:(_Bool)arg2;
@property(copy, nonatomic) CDUnknownBlockType switchValueChangeHandler; // @synthesize switchValueChangeHandler=_switchValueChangeHandler;
@property(nonatomic) _Bool value; // @synthesize value=_value;
- (void).cxx_destruct;
- (id)errors;
- (id)initWithTitle:(id)arg1 value:(_Bool)arg2 switchValueChangeHandler:(CDUnknownBlockType)arg3;
- (id)initWithTitle:(id)arg1 value:(_Bool)arg2;

@end

