//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITextField.h>

#import "UITextFieldDelegate-Protocol.h"

@class NSString;
@protocol UITextFieldDelegate;

@interface REFormattedNumberField : UITextField <UITextFieldDelegate>
{
    NSString *_format;
    NSString *_currentFormattedText;
    id <UITextFieldDelegate> _originalDelegate;
}

@property(nonatomic) __weak id <UITextFieldDelegate> originalDelegate; // @synthesize originalDelegate=_originalDelegate;
@property(copy, nonatomic) NSString *currentFormattedText; // @synthesize currentFormattedText=_currentFormattedText;
@property(copy, nonatomic) NSString *format; // @synthesize format=_format;
- (void).cxx_destruct;
- (_Bool)respondsToSelector:(SEL)arg1;
- (id)forwardingTargetForSelector:(SEL)arg1;
- (id)delegate;
- (void)setDelegate:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
@property(readonly, copy, nonatomic) NSString *unformattedText;
- (void)deleteBackward;
- (void)formatInput:(id)arg1;
- (id)string:(id)arg1 withNumberFormat:(id)arg2;
- (void)commonInit;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

