//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "REValidator.h"

@interface RELengthValidator : REValidator
{
}

+ (id)validateObject:(id)arg1 variableName:(id)arg2 parameters:(id)arg3;
+ (id)parseParameterString:(id)arg1;
+ (id)name;

@end

