//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RETextItem.h"

@class UIColor;

@interface RELongTextItem : RETextItem
{
    _Bool _editable;
    UIColor *_placeholderColor;
}

+ (id)itemWithValue:(id)arg1 placeholder:(id)arg2;
@property(nonatomic) _Bool editable; // @synthesize editable=_editable;
@property(retain, nonatomic) UIColor *placeholderColor; // @synthesize placeholderColor=_placeholderColor;
- (void).cxx_destruct;
- (id)initWithTitle:(id)arg1 value:(id)arg2 placeholder:(id)arg3;
- (id)initWithValue:(id)arg1 placeholder:(id)arg2;
- (id)init;

@end

