//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RETableViewItem.h"

@class NSArray;

@interface REMultipleChoiceItem : RETableViewItem
{
    NSArray *_value;
}

+ (id)itemWithTitle:(id)arg1 value:(id)arg2 selectionHandler:(CDUnknownBlockType)arg3;
@property(retain, nonatomic) NSArray *value; // @synthesize value=_value;
- (void).cxx_destruct;
- (id)errors;
- (id)initWithTitle:(id)arg1 value:(id)arg2 selectionHandler:(CDUnknownBlockType)arg3;

@end

