//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RETableViewItem.h"

@class NSArray, UIColor;

@interface RESegmentedItem : RETableViewItem
{
    long long _value;
    NSArray *_segmentedControlTitles;
    NSArray *_segmentedControlImages;
    UIColor *_tintColor;
    CDUnknownBlockType _switchValueChangeHandler;
}

+ (id)itemWithTitle:(id)arg1 segmentedControlImages:(id)arg2 value:(long long)arg3 switchValueChangeHandler:(CDUnknownBlockType)arg4;
+ (id)itemWithTitle:(id)arg1 segmentedControlImages:(id)arg2 value:(long long)arg3;
+ (id)itemWithTitle:(id)arg1 segmentedControlTitles:(id)arg2 value:(long long)arg3 switchValueChangeHandler:(CDUnknownBlockType)arg4;
+ (id)itemWithTitle:(id)arg1 segmentedControlTitles:(id)arg2 value:(long long)arg3;
@property(copy, nonatomic) CDUnknownBlockType switchValueChangeHandler; // @synthesize switchValueChangeHandler=_switchValueChangeHandler;
@property(retain, nonatomic) UIColor *tintColor; // @synthesize tintColor=_tintColor;
@property(copy, nonatomic) NSArray *segmentedControlImages; // @synthesize segmentedControlImages=_segmentedControlImages;
@property(copy, nonatomic) NSArray *segmentedControlTitles; // @synthesize segmentedControlTitles=_segmentedControlTitles;
@property(nonatomic) long long value; // @synthesize value=_value;
- (void).cxx_destruct;
- (id)initWithTitle:(id)arg1 segmentedControlImages:(id)arg2 value:(long long)arg3 switchValueChangeHandler:(CDUnknownBlockType)arg4;
- (id)initWithTitle:(id)arg1 segmentedControlImages:(id)arg2 value:(long long)arg3;
- (id)initWithTitle:(id)arg1 segmentedControlTitles:(id)arg2 value:(long long)arg3 switchValueChangeHandler:(CDUnknownBlockType)arg4;
- (id)initWithTitle:(id)arg1 segmentedControlTitles:(id)arg2 value:(long long)arg3;

@end

