//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSMutableDictionary;

@interface RETableViewCellStyle : NSObject <NSCopying>
{
    double _cellHeight;
    long long _defaultCellSelectionStyle;
    double _backgroundImageMargin;
    double _contentViewMargin;
    NSMutableDictionary *_backgroundImages;
    NSMutableDictionary *_selectedBackgroundImages;
}

@property(retain, nonatomic) NSMutableDictionary *selectedBackgroundImages; // @synthesize selectedBackgroundImages=_selectedBackgroundImages;
@property(retain, nonatomic) NSMutableDictionary *backgroundImages; // @synthesize backgroundImages=_backgroundImages;
@property(nonatomic) double contentViewMargin; // @synthesize contentViewMargin=_contentViewMargin;
@property(nonatomic) double backgroundImageMargin; // @synthesize backgroundImageMargin=_backgroundImageMargin;
@property(nonatomic) long long defaultCellSelectionStyle; // @synthesize defaultCellSelectionStyle=_defaultCellSelectionStyle;
@property(nonatomic) double cellHeight; // @synthesize cellHeight=_cellHeight;
- (void).cxx_destruct;
- (void)setSelectedBackgroundImage:(id)arg1 forCellType:(long long)arg2;
- (id)selectedBackgroundImageForCellType:(long long)arg1;
- (_Bool)hasCustomSelectedBackgroundImage;
- (void)setBackgroundImage:(id)arg1 forCellType:(long long)arg2;
- (id)backgroundImageForCellType:(long long)arg1;
- (_Bool)hasCustomBackgroundImage;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

