//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RETableViewCell.h"

@class RERadioItem, UILabel;

@interface RETableViewOptionCell : RETableViewCell
{
    _Bool _enabled;
    RERadioItem *_item;
    UILabel *_valueLabel;
}

@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(retain, nonatomic) UILabel *valueLabel; // @synthesize valueLabel=_valueLabel;
@property(retain, nonatomic) RERadioItem *item; // @synthesize item=_item;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)layoutSubviews;
- (void)cellWillAppear;
- (void)cellDidLoad;
- (void)dealloc;

@end

