//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

#import "RETableViewManagerDelegate-Protocol.h"

@class NSArray, NSString, RETableViewCellStyle, RETableViewItem, RETableViewManager, RETableViewSection;
@protocol RETableViewManagerDelegate;

@interface RETableViewOptionsController : UITableViewController <RETableViewManagerDelegate>
{
    _Bool _multipleChoice;
    RETableViewItem *_item;
    NSArray *_options;
    RETableViewManager *_tableViewManager;
    RETableViewSection *_mainSection;
    CDUnknownBlockType _completionHandler;
    RETableViewCellStyle *_style;
    id <RETableViewManagerDelegate> _delegate;
}

@property(nonatomic) __weak id <RETableViewManagerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) RETableViewCellStyle *style; // @synthesize style=_style;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
@property(nonatomic) _Bool multipleChoice; // @synthesize multipleChoice=_multipleChoice;
@property(retain, nonatomic) RETableViewSection *mainSection; // @synthesize mainSection=_mainSection;
@property(retain, nonatomic) RETableViewManager *tableViewManager; // @synthesize tableViewManager=_tableViewManager;
@property(retain, nonatomic) NSArray *options; // @synthesize options=_options;
@property(nonatomic) __weak RETableViewItem *item; // @synthesize item=_item;
- (void).cxx_destruct;
- (void)viewDidLoad;
- (id)initWithItem:(id)arg1 options:(id)arg2 multipleChoice:(_Bool)arg3 completionHandler:(CDUnknownBlockType)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

