//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RETableViewCell.h"

#import "UITextFieldDelegate-Protocol.h"

@class NSString, RECreditCardItem, REFormattedNumberField, UIImageView, UIView;

@interface RETableViewCreditCardCell : RETableViewCell <UITextFieldDelegate>
{
    _Bool _isNumberEditingMode;
    _Bool _enabled;
    RECreditCardItem *_item;
    UIView *_wrapperView;
    UIView *_creditCardImageViewContainer;
    UIImageView *_currentImageView;
    UIImageView *_creditCardBackImageView;
    UIImageView *_creditCardImageView;
    UIImageView *_creditCardStackImageView;
    REFormattedNumberField *_creditCardField;
    REFormattedNumberField *_expirationDateField;
    REFormattedNumberField *_cvvField;
    UIImageView *_ribbonExpired;
    struct CGSize _textFieldPositionOffset;
}

+ (_Bool)canFocus;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(nonatomic) _Bool isNumberEditingMode; // @synthesize isNumberEditingMode=_isNumberEditingMode;
@property(retain, nonatomic) UIImageView *ribbonExpired; // @synthesize ribbonExpired=_ribbonExpired;
@property(retain, nonatomic) REFormattedNumberField *cvvField; // @synthesize cvvField=_cvvField;
@property(retain, nonatomic) REFormattedNumberField *expirationDateField; // @synthesize expirationDateField=_expirationDateField;
@property(retain, nonatomic) REFormattedNumberField *creditCardField; // @synthesize creditCardField=_creditCardField;
@property(retain, nonatomic) UIImageView *creditCardStackImageView; // @synthesize creditCardStackImageView=_creditCardStackImageView;
@property(retain, nonatomic) UIImageView *creditCardImageView; // @synthesize creditCardImageView=_creditCardImageView;
@property(retain, nonatomic) UIImageView *creditCardBackImageView; // @synthesize creditCardBackImageView=_creditCardBackImageView;
@property(retain, nonatomic) UIImageView *currentImageView; // @synthesize currentImageView=_currentImageView;
@property(retain, nonatomic) UIView *creditCardImageViewContainer; // @synthesize creditCardImageViewContainer=_creditCardImageViewContainer;
@property(retain, nonatomic) UIView *wrapperView; // @synthesize wrapperView=_wrapperView;
@property(nonatomic) struct CGSize textFieldPositionOffset; // @synthesize textFieldPositionOffset=_textFieldPositionOffset;
@property(retain, nonatomic) RECreditCardItem *item; // @synthesize item=_item;
- (void).cxx_destruct;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (_Bool)textFieldShouldEndEditing:(id)arg1;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (void)textFieldDidChange:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)flipCreditCardImageViewBack:(id)arg1;
- (id)responder;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)layoutSubviews;
- (void)cellWillAppear;
- (void)cellDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

