//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RETableViewCell.h"

@class REInlineDatePickerItem, UIDatePicker;

@interface RETableViewInlineDatePickerCell : RETableViewCell
{
    _Bool _enabled;
    REInlineDatePickerItem *_item;
    UIDatePicker *_datePicker;
}

+ (double)heightWithItem:(id)arg1 tableViewManager:(id)arg2;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(retain, nonatomic) UIDatePicker *datePicker; // @synthesize datePicker=_datePicker;
@property(retain, nonatomic) REInlineDatePickerItem *item; // @synthesize item=_item;
- (void).cxx_destruct;
- (void)datePickerValueDidChange:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)layoutSubviews;
- (void)cellWillAppear;
- (void)cellDidLoad;
- (void)dealloc;

@end

