//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CAShapeLayer, UIColor;

@interface SVIndefiniteAnimatedView : UIView
{
    double _strokeThickness;
    double _radius;
    UIColor *_strokeColor;
    CAShapeLayer *_indefiniteAnimatedLayer;
}

@property(retain, nonatomic) CAShapeLayer *indefiniteAnimatedLayer; // @synthesize indefiniteAnimatedLayer=_indefiniteAnimatedLayer;
@property(retain, nonatomic) UIColor *strokeColor; // @synthesize strokeColor=_strokeColor;
@property(nonatomic) double radius; // @synthesize radius=_radius;
@property(nonatomic) double strokeThickness; // @synthesize strokeThickness=_strokeThickness;
- (void).cxx_destruct;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)layoutAnimatedLayer;
- (void)willMoveToSuperview:(id)arg1;

@end

