//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UILabel.h>

@class NSString, NSTimer, UILabelCounter;

@interface UICountingLabel : UILabel
{
    int _method;
    float _startingValue;
    float _destinationValue;
    float _easingRate;
    NSString *_format;
    double _animationDuration;
    CDUnknownBlockType _formatBlock;
    CDUnknownBlockType _attributedFormatBlock;
    CDUnknownBlockType _completionBlock;
    double _progress;
    double _lastUpdate;
    double _totalTime;
    NSTimer *_timer;
    UILabelCounter *_counter;
}

@property(retain, nonatomic) UILabelCounter *counter; // @synthesize counter=_counter;
@property(nonatomic) __weak NSTimer *timer; // @synthesize timer=_timer;
@property float easingRate; // @synthesize easingRate=_easingRate;
@property double totalTime; // @synthesize totalTime=_totalTime;
@property double lastUpdate; // @synthesize lastUpdate=_lastUpdate;
@property double progress; // @synthesize progress=_progress;
@property float destinationValue; // @synthesize destinationValue=_destinationValue;
@property float startingValue; // @synthesize startingValue=_startingValue;
@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
@property(copy, nonatomic) CDUnknownBlockType attributedFormatBlock; // @synthesize attributedFormatBlock=_attributedFormatBlock;
@property(copy, nonatomic) CDUnknownBlockType formatBlock; // @synthesize formatBlock=_formatBlock;
@property(nonatomic) double animationDuration; // @synthesize animationDuration=_animationDuration;
@property(nonatomic) int method; // @synthesize method=_method;
@property(retain, nonatomic) NSString *format; // @synthesize format=_format;
- (void).cxx_destruct;
- (double)currentValue;
- (void)runCompletionBlock;
- (void)setTextValue:(float)arg1;
- (void)updateValue:(id)arg1;
- (void)countFromZeroTo:(float)arg1 withDuration:(double)arg2;
- (void)countFromZeroTo:(float)arg1;
- (void)countFromCurrentValueTo:(float)arg1 withDuration:(double)arg2;
- (void)countFromCurrentValueTo:(float)arg1;
- (void)countFrom:(float)arg1 to:(float)arg2 withDuration:(double)arg3;
- (void)countFrom:(float)arg1 to:(float)arg2;

@end

