//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class AVCaptureDevice, AVCaptureSession, CALayer, UIColor, UILabel, UIPinchGestureRecognizer, ZBarCaptureReader, ZBarImageScanner;
@protocol ZBarReaderViewDelegate;

@interface ZBarReaderView : UIView
{
    id <ZBarReaderViewDelegate> readerDelegate;
    ZBarCaptureReader *captureReader;
    struct CGRect scanCrop;
    struct CGRect effectiveCrop;
    struct CGAffineTransform previewTransform;
    double zoom;
    double zoom0;
    double maxZoom;
    UIColor *trackingColor;
    _Bool tracksSymbols;
    _Bool showsFPS;
    long long torchMode;
    long long interfaceOrientation;
    double animationDuration;
    CALayer *preview;
    CALayer *overlay;
    CALayer *tracking;
    CALayer *cropLayer;
    UIView *fpsView;
    UILabel *fpsLabel;
    UIPinchGestureRecognizer *pinch;
    double imageScale;
    struct CGSize imageSize;
    _Bool started;
    _Bool running;
    _Bool locked;
}

+ (id)alloc;
@property(readonly, nonatomic) ZBarCaptureReader *captureReader; // @synthesize captureReader;
@property(nonatomic) struct CGAffineTransform previewTransform; // @synthesize previewTransform;
@property(nonatomic) struct CGRect scanCrop; // @synthesize scanCrop;
@property(nonatomic) double maxZoom; // @synthesize maxZoom;
@property(nonatomic) double zoom; // @synthesize zoom;
@property(nonatomic) _Bool showsFPS; // @synthesize showsFPS;
@property(nonatomic) long long torchMode; // @synthesize torchMode;
@property(retain, nonatomic) UIColor *trackingColor; // @synthesize trackingColor;
@property(nonatomic) _Bool tracksSymbols; // @synthesize tracksSymbols;
@property(nonatomic) id <ZBarReaderViewDelegate> readerDelegate; // @synthesize readerDelegate;
- (void)didTrackSymbols:(id)arg1;
- (void)updateTracking:(id)arg1 withSymbol:(id)arg2;
- (void)handlePinch;
- (void)flushCache;
- (void)stop;
- (void)start;
- (void)setZoom:(double)arg1 animated:(_Bool)arg2;
@property(nonatomic) _Bool allowsPinchZoom; // @dynamic allowsPinchZoom;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)setImageSize:(struct CGSize)arg1;
- (void)layoutSubviews;
- (void)updateCrop;
- (void)resetTracking;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (id)initWithImageScanner:(id)arg1;
- (void)_initWithImageScanner:(id)arg1;
- (void)initSubviews;

// Remaining properties
@property(retain, nonatomic) AVCaptureDevice *device; // @dynamic device;
@property(nonatomic) _Bool enableCache; // @dynamic enableCache;
@property(readonly, nonatomic) ZBarImageScanner *scanner; // @dynamic scanner;
@property(readonly, nonatomic) AVCaptureSession *session; // @dynamic session;

@end

