//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UIImage, ZBarSymbolSet;

@interface ZBarImage : NSObject
{
    struct zbar_image_s *zimg;
    double t_convert;
}

+ (unsigned long long)fourcc:(id)arg1;
- (void)cleanup;
@property(readonly, nonatomic) UIImage *UIImage; // @dynamic UIImage;
- (id)UIImageWithOrientation:(long long)arg1;
@property(readonly, nonatomic) struct zbar_image_s *zbarImage; // @dynamic zbarImage;
- (void)setData:(const void *)arg1 withLength:(unsigned long long)arg2;
@property(readonly, nonatomic) unsigned long long dataLength; // @dynamic dataLength;
@property(readonly, nonatomic) const void *data; // @dynamic data;
@property(copy, nonatomic) ZBarSymbolSet *symbols; // @dynamic symbols;
@property(nonatomic) struct CGRect crop; // @dynamic crop;
@property(nonatomic) struct CGSize size; // @dynamic size;
@property(nonatomic) unsigned int sequence; // @dynamic sequence;
@property(nonatomic) unsigned long long format; // @dynamic format;
- (struct zbar_image_s *)image;
- (id)initWithCGImage:(struct CGImage *)arg1;
- (id)initWithCGImage:(struct CGImage *)arg1 size:(struct CGSize)arg2;
- (id)initWithCGImage:(struct CGImage *)arg1 crop:(struct CGRect)arg2 size:(struct CGSize)arg3;
- (void)dealloc;
- (id)init;
- (id)initWithImage:(struct zbar_image_s *)arg1;

@end

