//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class UIView, ZBarCameraSimulator, ZBarHelpController, ZBarImageScanner, ZBarReaderView;
@protocol ZBarReaderDelegate;

@interface ZBarReaderViewController : UIViewController
{
    ZBarImageScanner *scanner;
    id <ZBarReaderDelegate> readerDelegate;
    ZBarReaderView *readerView;
    UIView *cameraOverlayView;
    struct CGAffineTransform cameraViewTransform;
    struct CGRect scanCrop;
    unsigned long long supportedOrientationsMask;
    long long cameraDevice;
    long long cameraFlashMode;
    long long videoQuality;
    _Bool showsZBarControls;
    _Bool tracksSymbols;
    _Bool enableCache;
    ZBarHelpController *helpController;
    UIView *controls;
    UIView *shutter;
    _Bool didHideStatusBar;
    _Bool rotating;
    ZBarCameraSimulator *cameraSim;
}

+ (id)availableCaptureModesForCameraDevice:(long long)arg1;
+ (_Bool)isFlashAvailableForCameraDevice:(long long)arg1;
+ (_Bool)isCameraDeviceAvailable:(long long)arg1;
+ (_Bool)isSourceTypeAvailable:(long long)arg1;
@property(nonatomic) struct CGRect scanCrop; // @synthesize scanCrop;
@property(nonatomic) long long videoQuality; // @synthesize videoQuality;
@property(nonatomic) long long cameraFlashMode; // @synthesize cameraFlashMode;
@property(nonatomic) long long cameraDevice; // @synthesize cameraDevice;
@property(nonatomic) struct CGAffineTransform cameraViewTransform; // @synthesize cameraViewTransform;
@property(retain, nonatomic) UIView *cameraOverlayView; // @synthesize cameraOverlayView;
@property(nonatomic) _Bool enableCache; // @synthesize enableCache;
@property(nonatomic) _Bool tracksSymbols; // @synthesize tracksSymbols;
@property(nonatomic) unsigned long long supportedOrientationsMask; // @synthesize supportedOrientationsMask;
@property(nonatomic) _Bool showsZBarControls; // @synthesize showsZBarControls;
@property(nonatomic) id <ZBarReaderDelegate> readerDelegate; // @synthesize readerDelegate;
@property(readonly, nonatomic) ZBarImageScanner *scanner; // @synthesize scanner;
@property(nonatomic) long long maxScanDimension; // @dynamic maxScanDimension;
@property(nonatomic) _Bool takesPicture; // @dynamic takesPicture;
@property(nonatomic) int cameraMode; // @dynamic cameraMode;
@property(nonatomic) _Bool showsHelpOnFail; // @dynamic showsHelpOnFail;
@property(nonatomic) _Bool showsCameraControls; // @dynamic showsCameraControls;
@property(nonatomic) _Bool allowsImageEditing; // @dynamic allowsImageEditing;
@property(nonatomic) _Bool allowsEditing; // @dynamic allowsEditing;
@property(nonatomic) long long sourceType; // @dynamic sourceType;
- (void)readerViewDidStart:(id)arg1;
- (void)readerView:(id)arg1 didReadSymbols:(id)arg2 fromImage:(id)arg3;
- (void)removeHelp:(id)arg1 done:(id)arg2 context:(void *)arg3;
- (void)helpControllerDidFinish:(id)arg1;
@property(nonatomic) long long cameraCaptureMode;
- (void)takePicture;
- (void)showHelpWithReason:(id)arg1;
- (void)info;
- (void)cancel;
@property(readonly, nonatomic) ZBarReaderView *readerView; // @synthesize readerView;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)dismissModalViewControllerAnimated:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)loadView;
- (void)initVideoQuality;
- (void)initControls;
- (void)dealloc;
- (void)cleanup;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (void)_init;

@end

