//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ZBarReaderView.h"

@class AVCaptureDevice, AVCaptureInput, AVCaptureSession;

@interface ZBarReaderViewImpl : ZBarReaderView
{
    AVCaptureSession *session;
    AVCaptureDevice *device;
    AVCaptureInput *input;
}

- (id)session;
- (id)device;
- (void)captureReader:(id)arg1 didReadNewSymbolsFromImage:(id)arg2;
- (void)captureReader:(id)arg1 didTrackSymbols:(id)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)onVideoError:(id)arg1;
- (void)onVideoStop:(id)arg1;
- (void)onVideoStart:(id)arg1;
- (void)lockDevice;
- (void)configureDevice;
- (void)flushCache;
- (void)stop;
- (void)start;
- (void)setShowsFPS:(_Bool)arg1;
- (void)setTorchMode:(long long)arg1;
- (void)setEnableCache:(_Bool)arg1;
- (_Bool)enableCache;
- (void)setDevice:(id)arg1;
- (id)scanner;
- (void)updateCrop;
- (void)dealloc;
- (void)initSubviews;
- (void)_initWithImageScanner:(id)arg1;

@end

